//! Local + Stripe Checkout columns for `phpyun_rs_stripe_order`.

pub struct LocalOrderIn<'a> {
    pub uid: u64,
    pub usertype: i32,
    pub order_no: &'a str,
    pub company_order_id: u64,
    pub order_kind: i32,
    pub package_code: &'a str,
    pub rating: i32,
    pub subject: &'a str,
    pub amount_cents: i32,
    pub amount_yuan: f64,
    pub channel: &'a str,
    pub order_state: i32,
    pub client_ip: &'a str,
    pub success_path: &'a str,
    pub created_at: i64,
}

pub struct RequestPatch<'a> {
    pub req_mode: &'a str,
    pub req_ui_mode: &'a str,
    pub req_currency: &'a str,
    pub req_unit_amount: i32,
    pub req_product_name: &'a str,
    pub req_quantity: i32,
    pub req_success_url: &'a str,
    pub req_cancel_url: &'a str,
    pub req_client_reference_id: &'a str,
    pub req_customer_email: &'a str,
    pub req_metadata_json: Option<&'a str>,
    pub req_body: &'a str,
    pub req_stripe_version: &'a str,
    pub req_at: i64,
}

pub struct SessionPatch {
    pub stripe_session_id: String,
    pub stripe_object: String,
    pub stripe_livemode: i32,
    pub stripe_created: i64,
    pub stripe_expires_at: i64,
    pub stripe_status: String,
    pub stripe_payment_status: String,
    pub stripe_mode: String,
    pub stripe_ui_mode: String,
    pub stripe_currency: String,
    pub stripe_amount_subtotal: Option<i32>,
    pub stripe_amount_total: Option<i32>,
    pub stripe_amount_discount: Option<i32>,
    pub stripe_amount_shipping: Option<i32>,
    pub stripe_amount_tax: Option<i32>,
    pub stripe_customer: String,
    pub stripe_customer_email: String,
    pub stripe_customer_account: String,
    pub stripe_customer_creation: String,
    pub stripe_customer_name: String,
    pub stripe_customer_phone: String,
    pub stripe_customer_tax_exempt: String,
    pub stripe_payment_intent: String,
    pub stripe_payment_link: String,
    pub stripe_setup_intent: String,
    pub stripe_subscription: String,
    pub stripe_invoice: String,
    pub stripe_url: String,
    pub stripe_success_url: String,
    pub stripe_cancel_url: String,
    pub stripe_return_url: String,
    pub stripe_client_reference_id: String,
    pub stripe_locale: String,
    pub stripe_submit_type: String,
    pub stripe_billing_address_collection: String,
    pub stripe_payment_method_collection: String,
    pub stripe_payment_method_types: String,
    pub stripe_allowed_payment_method_types: String,
    pub stripe_excluded_payment_method_types: String,
    pub stripe_allow_promotion_codes: Option<i32>,
    pub stripe_recovered_from: String,
    pub stripe_redirect_on_completion: String,
    pub stripe_origin_context: String,
    pub stripe_integration_identifier: String,
    pub stripe_automatic_tax_enabled: Option<i32>,
    pub stripe_automatic_tax_status: String,
    pub stripe_payment_method: String,
    pub stripe_latest_charge: String,
    pub stripe_adaptive_pricing_json: Option<String>,
    pub stripe_after_expiration_json: Option<String>,
    pub stripe_automatic_tax_json: Option<String>,
    pub stripe_branding_settings_json: Option<String>,
    pub stripe_collected_information_json: Option<String>,
    pub stripe_consent_json: Option<String>,
    pub stripe_consent_collection_json: Option<String>,
    pub stripe_custom_fields_json: Option<String>,
    pub stripe_custom_text_json: Option<String>,
    pub stripe_customer_details_json: Option<String>,
    pub stripe_currency_conversion_json: Option<String>,
    pub stripe_discounts_json: Option<String>,
    pub stripe_invoice_creation_json: Option<String>,
    pub stripe_line_items_json: Option<String>,
    pub stripe_metadata_json: Option<String>,
    pub stripe_name_collection_json: Option<String>,
    pub stripe_optional_items_json: Option<String>,
    pub stripe_payment_method_options_json: Option<String>,
    pub stripe_payment_method_configuration_json: Option<String>,
    pub stripe_permissions_json: Option<String>,
    pub stripe_phone_number_collection_json: Option<String>,
    pub stripe_presentment_details_json: Option<String>,
    pub stripe_saved_payment_method_options_json: Option<String>,
    pub stripe_shipping_address_collection_json: Option<String>,
    pub stripe_shipping_cost_json: Option<String>,
    pub stripe_shipping_options_json: Option<String>,
    pub stripe_tax_id_collection_json: Option<String>,
    pub stripe_total_details_json: Option<String>,
    pub stripe_wallet_options_json: Option<String>,
    pub stripe_managed_payments_json: Option<String>,
    pub stripe_session_json: Option<String>,
}

pub struct EventPatch<'a> {
    pub stripe_event_id: &'a str,
    pub stripe_event_type: &'a str,
    pub stripe_event_created: i64,
    pub stripe_api_version: &'a str,
    pub stripe_event_json: Option<&'a str>,
}

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct StripeOrderRow {
    pub uid: u64,
    pub usertype: i32,
    pub order_no: String,
    pub amount_cents: i32,
    pub settled: i32,
    pub stripe_session_id: String,
    pub stripe_payment_status: String,
    pub stripe_amount_total: Option<i32>,
    pub stripe_payment_intent: String,
}
