import type { Component } from 'vue'
import { defineAsyncComponent } from 'vue'
import PhpPending from '~/components/PhpPending.vue'

/** PHP router.js path (without slash) -> existing Nuxt screen. Unmapped paths render PhpPending. */
const loaders: Record<string, () => Promise<{ default: Component }>> = {
  index: () => import('~/pages/index.vue'),
  jobtai: () => import('~/pages/jobs/index.vue'),
  companyjob: () => import('~/pages/jobs/index.vue'),
  weipin_tiny: () => import('~/pages/jobs/tiny.vue'),
  weipin_once: () => import('~/pages/jobs/once.vue'),
  companycrm: () => import('~/pages/companies/index.vue'),
  resume: () => import('~/pages/resumes/index.vue'),
  userscrm: () => import('~/pages/users/index.vue'),
  companyrz: () => import('~/pages/certs/index.vue'),
  renzheng: () => import('~/pages/certs/index.vue'),
  feedback: () => import('~/pages/feedback/index.vue'),
  question: () => import('~/pages/content/questions.vue'),
  announcement: () => import('~/pages/content/announcements.vue'),
  newsmanage: () => import('~/pages/content/articles.vue'),
  xczph: () => import('~/pages/content/fairs.vue'),
  special: () => import('~/pages/content/specials.vue'),
  ad: () => import('~/pages/ads/index.vue'),
  shopreward: () => import('~/pages/redeem/rewards.vue'),
  shoplist: () => import('~/pages/redeem/orders.vue'),
  shopclass: () => import('~/pages/redeem/classes.vue'),
  user: () => import('~/pages/system/admins.vue'),
  myaccount: () => import('~/pages/system/admins.vue'),
  ugroup: () => import('~/pages/system/rbac.vue'),
  logrecord: () => import('~/pages/ops/audit.vue'),
  userlog: () => import('~/pages/ops/audit.vue'),
  userloginlog: () => import('~/pages/ops/login-logs.vue'),
  set: () => import('~/pages/system/settings.vue'),
  moduleset: () => import('~/pages/system/settings.vue'),
  yemainset: () => import('~/pages/system/settings.vue'),
  payset: () => import('~/pages/system/settings.vue'),
  jifenset: () => import('~/pages/system/settings.vue'),
  regset: () => import('~/pages/system/settings.vue'),
  seoset: () => import('~/pages/system/seo.vue'),
  emailset: () => import('~/pages/system/email.vue'),
  messageset: () => import('~/pages/system/sms.vue'),
  messagelog: () => import('~/pages/system/sms.vue'),
  weixinmenu: () => import('~/pages/system/weixin.vue'),
  weixinrecord: () => import('~/pages/system/weixin.vue'),
  cron: () => import('~/pages/system/cron.vue'),
  city: () => import('~/pages/system/geo.vue'),
  job_class: () => import('~/pages/categories/index.vue'),
  industry: () => import('~/pages/categories/index.vue'),
  member_index: () => import('~/pages/categories/index.vue'),
  partclass: () => import('~/pages/categories/index.vue'),
  reason: () => import('~/pages/categories/index.vue'),
  question_class: () => import('~/pages/categories/index.vue'),
  navigation: () => import('~/pages/nav/index.vue'),
  dataRecycle: () => import('~/pages/ops/recycle.vue'),
  warning: () => import('~/pages/ops/warnings.vue'),
  chongzhidd: () => import('~/pages/orders/index.vue'),
  houtaicz: () => import('~/pages/finance/recharge.vue'),
  reportjob: () => import('~/pages/reports/index.vue'),
  reportresume: () => import('~/pages/reports/index.vue'),
  reportask: () => import('~/pages/reports/index.vue'),
  reportadvise: () => import('~/pages/reports/index.vue'),
  gzmanage: () => import('~/pages/content/gongzhao.vue'),
  friendlink: () => import('~/pages/content/links.vue'),
}

export const PHP_TEMPLATES: Record<string, string> = {
  ad: 'yunying/ad/ad.html',
  ad_class: 'yunying/ad/ad_class.html',
  addgg: 'neirong/gg/addgg.html',
  addgz: 'neirong/gz/addgz.html',
  addpubtemp: 'tool/weixin/addpubtemp.html',
  admin_nav: 'system/set/admin_nav.html',
  admin_uc: 'tool/login/admin_uc.html',
  announcement: 'neirong/announcement/index.html',
  chcompany: 'neirong/zph/chcompany.html',
  chongzhidd: 'yunying/caiwu/chongzhidd.html',
  city: 'system/category/city.html',
  companycrm: 'user/company/companycrm.html',
  companyjob: 'user/company/companyjob.html',
  companyjoblog: 'user/company/companyjoblog.html',
  companylog: 'user/company/companylog.html',
  companyms: 'user/company/companyms.html',
  companyrz: 'user/company/companyrz.html',
  companyset: 'user/company/companyset.html',
  companyvip: 'user/company/companyvip.html',
  cpfl: 'neirong/cp/cpfl.html',
  cpsj: 'neirong/cp/cpsj.html',
  cron: 'system/set/cron.html',
  dataBoard: 'tool/database/dataBoard.html',
  dataCall: 'tool/database/dataCall.html',
  dataCollection: 'tool/database/dataCollection.html',
  dataOss: 'tool/database/dataOss.html',
  dataRecycle: 'tool/database/dataRecycle.html',
  database: 'tool/database/database.html',
  domainAdminList: 'system/domain/domainAdminList.html',
  domainList: 'system/domain/domainList.html',
  emaillog: 'tool/email/emaillog.html',
  emailset: 'tool/email/emailset.html',
  errorlog: 'system/info/errorlog.html',
  fabutool: 'tool/weixin/fabutool.html',
  fastlogin: 'tool/login/fastlogin.html',
  feedback: 'system/info/feedback.html',
  friendlink: 'system/set/friendlink.html',
  generate_cache: 'tool/generate/generate_cache.html',
  generate_page: 'tool/generate/generate_page.html',
  generate_xml: 'tool/generate/generate_xml.html',
  gsdConfig: 'tool/database/gsdConfig.html',
  guanjianci: 'system/set/guanjianci.html',
  gzmanage: 'neirong/gz/gzmanage.html',
  houtaicz: 'yunying/caiwu/houtaicz.html',
  index: 'index/index/index.html',
  industry: 'system/category/industry.html',
  introduce_class: 'system/category/introduce_class.html',
  jifenset: 'system/set/jifenset.html',
  job_class: 'system/category/job_class.html',
  jobtai: 'user/company/companyjob.html',
  logrecord: 'system/role/logrecord.html',
  lymanage: 'neirong/cp/lymanage.html',
  member_index: 'system/category/member_index.html',
  messagelog: 'tool/message/messagelog.html',
  messageset: 'tool/message/messageset.html',
  moduleset: 'system/set/moduleset.html',
  myaccount: 'system/role/myaccount.html',
  navigation: 'system/set/navigation.html',
  navmap: 'system/set/navmap.html',
  newslb: 'neirong/news/newslb.html',
  newsmanage: 'neirong/news/newsmanage.html',
  newssx: 'neirong/news/newssx.html',
  notice: 'system/role/notice.html',
  partclass: 'system/category/partclass.html',
  payset: 'system/set/payset.html',
  qdm: 'tool/weixin/qdm.html',
  question: 'neirong/question/index.html',
  question_class: 'neirong/question/class.html',
  question_config: 'neirong/question/config.html',
  reason: 'system/category/reason.html',
  regset: 'system/set/regset.html',
  renzheng: 'user/users/renzheng.html',
  reportadvise: 'yunying/jubao/reportadvise.html',
  reportask: 'yunying/jubao/reportask.html',
  reportjob: 'yunying/jubao/reportjob.html',
  reportresume: 'yunying/jubao/reportresume.html',
  resume: 'user/users/resume.html',
  schoolclass: 'system/category/schoolclass.html',
  seoset: 'system/set/seoset.html',
  set: 'system/set/index.html',
  shopclass: 'yunying/shop/shopclass.html',
  shoplist: 'yunying/shop/shoplist.html',
  shopreward: 'yunying/shop/shopreward.html',
  shopset: 'yunying/shop/shopset.html',
  singleclass: 'system/single/singleclass.html',
  singlepage: 'system/single/singlepage.html',
  special: 'yunying/special/special.html',
  systeminfo: 'system/info/system.html',
  toolbox_class: 'neirong/toolbox/class.html',
  toolbox_doc: 'neirong/toolbox/doc.html',
  tplset: 'system/set/tplset.html',
  tuiguangren: 'yunying/yingxiao/tuiguangren.html',
  ugroup: 'system/role/ugroup.html',
  user: 'system/role/user.html',
  usercrm: 'user/member/usercrm.html',
  usergj: 'user/member/usergj.html',
  userlog: 'user/member/userlog.html',
  userloginlog: 'user/member/userloginlog.html',
  userscrm: 'user/users/userscrm.html',
  userset: 'user/users/userset.html',
  version: 'system/set/version.html',
  warning: 'system/set/warning.html',
  weipin_once: 'user/weipin/once.html',
  weipin_tiny: 'user/weipin/tiny.html',
  weixinmenu: 'tool/weixin/weixinmenu.html',
  weixinrecord: 'tool/weixin/weixinrecord.html',
  xczph: 'neirong/zph/xczph.html',
  xiaofei: 'yunying/caiwu/xiaofei.html',
  xiaofeitj: 'yunying/caiwu/xiaofeitj.html',
  xingwei: 'user/users/xingwei.html',
  yemainset: 'system/set/yemainset.html',
  yhjl: 'neirong/cp/yhjl.html',
  yingxiao_hbconfig: 'yunying/yingxiao/hbconfig.html',
  yingxiao_hrlog: 'yunying/yingxiao/hrlog.html',
  yingxiao_tuiguang: 'yunying/yingxiao/tuiguang.html',
  zhcguanjianci: 'yunying/zhuanchang/zhcguanjianci.html',
  zhuancanzp: 'yunying/zhuanchang/zhuancanzp.html',
  zixun: 'user/users/zixun.html',
  zphaddress: 'neirong/zph/zphaddress.html',
}

export function resolvePhpScreen(phpPath: string): Component {
  const key = String(phpPath || '').replace(/^\//, '')
  const loader = loaders[key]
  if (loader) return defineAsyncComponent(loader)
  return PhpPending
}

