-- English names for phpyun_job_class (kind=job).
-- Same catalog is bundled at crates/products/recruit/services/data/job-en.json.
-- INSERT IGNORE so admin edits in phpyun_dict_i18n are kept.
INSERT IGNORE INTO `phpyun_dict_i18n` (`kind`, `item_id`, `lang`, `text`) VALUES
('job', 955, 'en', 'Technology'),
('job', 956, 'en', 'Backend Development'),
('job', 957, 'en', 'Full-stack Engineer'),
('job', 958, 'en', 'Rust Engineer'),
('job', 959, 'en', 'Backend Development'),
('job', 960, 'en', 'Java'),
('job', 961, 'en', 'C++'),
('job', 962, 'en', 'PHP'),
('job', 963, 'en', 'Data Mining'),
('job', 964, 'en', 'C'),
('job', 965, 'en', 'C#'),
('job', 966, 'en', '.NET'),
('job', 967, 'en', 'Hadoop'),
('job', 968, 'en', 'Python'),
('job', 969, 'en', 'Delphi'),
('job', 970, 'en', 'VB'),
('job', 971, 'en', 'Perl'),
('job', 972, 'en', 'Ruby'),
('job', 973, 'en', 'Node.js'),
('job', 974, 'en', 'Golang'),
('job', 975, 'en', 'Erlang'),
('job', 976, 'en', 'Audio / Video / Graphics Development'),
('job', 977, 'en', 'Data Collection'),
('job', 978, 'en', 'Mobile Development'),
('job', 979, 'en', 'UE4'),
('job', 980, 'en', 'Mobile Development'),
('job', 981, 'en', 'HTML5'),
('job', 982, 'en', 'Android'),
('job', 983, 'en', 'iOS'),
('job', 984, 'en', 'Windows Phone'),
('job', 985, 'en', 'Mobile Web Frontend'),
('job', 986, 'en', 'Flutter Development'),
('job', 987, 'en', 'JavaScript'),
('job', 988, 'en', 'Unity3D'),
('job', 989, 'en', 'Cocos2d-x'),
('job', 990, 'en', 'Testing'),
('job', 991, 'en', 'Penetration Testing'),
('job', 992, 'en', 'Test Engineer'),
('job', 993, 'en', 'Automation Testing'),
('job', 994, 'en', 'Functional Testing'),
('job', 995, 'en', 'Performance Testing'),
('job', 996, 'en', 'Test Development'),
('job', 997, 'en', 'Mobile Testing'),
('job', 998, 'en', 'Game Testing'),
('job', 999, 'en', 'Hardware Testing'),
('job', 1000, 'en', 'Software Testing'),
('job', 1001, 'en', 'Ops / Tech Support'),
('job', 1002, 'en', 'Operations Engineer'),
('job', 1003, 'en', 'DevOps Engineer'),
('job', 1004, 'en', 'Network Engineer'),
('job', 1005, 'en', 'Systems Engineer'),
('job', 1006, 'en', 'IT Support'),
('job', 1007, 'en', 'System Administrator'),
('job', 1008, 'en', 'Network Security'),
('job', 1009, 'en', 'System Security'),
('job', 1010, 'en', 'DBA'),
('job', 1011, 'en', 'Data'),
('job', 1012, 'en', 'Data'),
('job', 1013, 'en', 'ETL Engineer'),
('job', 1014, 'en', 'Data Warehouse'),
('job', 1015, 'en', 'Data Development'),
('job', 1016, 'en', 'Data Mining'),
('job', 1017, 'en', 'Data Analyst'),
('job', 1018, 'en', 'Data Architect'),
('job', 1019, 'en', 'Project Management'),
('job', 1020, 'en', 'Hardware Project Manager'),
('job', 1021, 'en', 'Project Manager'),
('job', 1022, 'en', 'Project Supervisor'),
('job', 1023, 'en', 'Project Assistant'),
('job', 1024, 'en', 'Project Specialist'),
('job', 1025, 'en', 'Implementation Consultant'),
('job', 1026, 'en', 'Implementation Engineer'),
('job', 1027, 'en', 'Requirements Engineer'),
('job', 1028, 'en', 'Hardware Development'),
('job', 1029, 'en', 'Hardware Engineer'),
('job', 1030, 'en', 'MCU'),
('job', 1031, 'en', 'Circuit Design'),
('job', 1032, 'en', 'Driver Development'),
('job', 1033, 'en', 'System Integration'),
('job', 1034, 'en', 'FPGA Development'),
('job', 1035, 'en', 'DSP Development'),
('job', 1036, 'en', 'ARM Development'),
('job', 1037, 'en', 'PCB Process'),
('job', 1038, 'en', 'RF Engineer'),
('job', 1039, 'en', 'Frontend Development'),
('job', 1040, 'en', 'Frontend Development'),
('job', 1041, 'en', 'Web Frontend'),
('job', 1042, 'en', 'JavaScript'),
('job', 1043, 'en', 'Flash Development'),
('job', 1044, 'en', 'HTML5'),
('job', 1045, 'en', 'Communications'),
('job', 1046, 'en', 'Communications Engineer'),
('job', 1047, 'en', 'Communications R&D Engineer'),
('job', 1048, 'en', 'Data Communications Engineer'),
('job', 1049, 'en', 'Mobile Communications Engineer'),
('job', 1050, 'en', 'Telecom Network Engineer'),
('job', 1051, 'en', 'Telecom Switching Engineer'),
('job', 1052, 'en', 'Wired Transmission Engineer'),
('job', 1053, 'en', 'Wireless RF Engineer'),
('job', 1054, 'en', 'Communications Power Engineer'),
('job', 1055, 'en', 'Communications Standards Engineer'),
('job', 1056, 'en', 'Communications Project Specialist'),
('job', 1057, 'en', 'Communications Project Manager'),
('job', 1058, 'en', 'Core Network Engineer'),
('job', 1059, 'en', 'Communications Test Engineer'),
('job', 1060, 'en', 'Communications Equipment Engineer'),
('job', 1061, 'en', 'Optical Communications Engineer'),
('job', 1062, 'en', 'Optical Transmission Engineer'),
('job', 1063, 'en', 'Optical Network Engineer'),
('job', 1064, 'en', 'Electronics / Semiconductor'),
('job', 1065, 'en', 'Electronics Engineer'),
('job', 1066, 'en', 'Electrical Engineer'),
('job', 1067, 'en', 'FAE'),
('job', 1068, 'en', 'Electrical Design Engineer'),
('job', 1069, 'en', 'Senior Technical Jobs'),
('job', 1070, 'en', 'Senior Technical Jobs'),
('job', 1071, 'en', 'Technical Manager'),
('job', 1072, 'en', 'Technical Director'),
('job', 1073, 'en', 'Test Manager'),
('job', 1074, 'en', 'Architect (IT)'),
('job', 1075, 'en', 'CTO'),
('job', 1076, 'en', 'Operations Director (IT)'),
('job', 1077, 'en', 'Technical Partner'),
('job', 1078, 'en', 'Artificial Intelligence'),
('job', 1079, 'en', 'Autonomous Driving Engineer'),
('job', 1080, 'en', 'Anti-fraud / Risk Algorithms'),
('job', 1081, 'en', 'Artificial Intelligence'),
('job', 1082, 'en', 'Search Algorithms'),
('job', 1083, 'en', 'NLP'),
('job', 1084, 'en', 'Recommendation Algorithms'),
('job', 1085, 'en', 'Algorithm Engineer'),
('job', 1086, 'en', 'Machine Learning'),
('job', 1087, 'en', 'Deep Learning'),
('job', 1088, 'en', 'Speech Recognition'),
('job', 1089, 'en', 'Image Recognition'),
('job', 1090, 'en', 'Algorithm Researcher'),
('job', 1091, 'en', 'Sales Technical Support'),
('job', 1092, 'en', 'Sales Technical Support'),
('job', 1093, 'en', 'Pre-sales Engineer'),
('job', 1094, 'en', 'After-sales Engineer'),
('job', 1095, 'en', 'Other Technical Jobs'),
('job', 1096, 'en', 'Other Technical Jobs'),
('job', 1097, 'en', 'Product'),
('job', 1098, 'en', 'Product Manager'),
('job', 1099, 'en', 'Hardware Product Manager'),
('job', 1100, 'en', 'Product Manager'),
('job', 1101, 'en', 'Web Product Manager'),
('job', 1102, 'en', 'Mobile Product Manager'),
('job', 1103, 'en', 'Product Assistant'),
('job', 1104, 'en', 'Data Product Manager'),
('job', 1105, 'en', 'E-commerce Product Manager'),
('job', 1106, 'en', 'Game Designer'),
('job', 1107, 'en', 'Product Specialist'),
('job', 1108, 'en', 'Senior Product Jobs'),
('job', 1109, 'en', 'Senior Product Jobs'),
('job', 1110, 'en', 'Product Director'),
('job', 1111, 'en', 'Game Producer'),
('job', 1112, 'en', 'VP of Product'),
('job', 1113, 'en', 'Other Product Jobs'),
('job', 1114, 'en', 'Other Product Jobs'),
('job', 1115, 'en', 'Design'),
('job', 1116, 'en', 'Visual Design'),
('job', 1117, 'en', 'Comic Artist'),
('job', 1118, 'en', 'Portrait Retoucher'),
('job', 1119, 'en', 'Visual Design'),
('job', 1120, 'en', 'Visual Designer'),
('job', 1121, 'en', 'Web Designer'),
('job', 1122, 'en', 'Flash Designer'),
('job', 1123, 'en', 'App Designer'),
('job', 1124, 'en', 'UI Designer'),
('job', 1125, 'en', 'Graphic Designer'),
('job', 1126, 'en', '3D Designer'),
('job', 1127, 'en', 'Advertising Designer'),
('job', 1128, 'en', 'Multimedia Designer'),
('job', 1129, 'en', 'Concept Artist'),
('job', 1130, 'en', 'Game VFX'),
('job', 1131, 'en', 'Game UI Designer'),
('job', 1132, 'en', 'Game Environment Art'),
('job', 1133, 'en', 'Game Character Art'),
('job', 1134, 'en', 'Game Animation'),
('job', 1135, 'en', 'CAD Design / Drafting'),
('job', 1136, 'en', 'Graphic Artist'),
('job', 1137, 'en', 'Packaging Design'),
('job', 1138, 'en', 'Design Assistant'),
('job', 1139, 'en', 'Animation Designer'),
('job', 1140, 'en', 'Illustrator'),
('job', 1141, 'en', 'Interaction Design'),
('job', 1142, 'en', 'Interaction Designer'),
('job', 1143, 'en', 'Mobile Interaction Designer'),
('job', 1144, 'en', 'Web Interaction Designer'),
('job', 1145, 'en', 'Hardware Interaction Designer'),
('job', 1146, 'en', 'User Research'),
('job', 1147, 'en', 'Data Analyst'),
('job', 1148, 'en', 'User Researcher'),
('job', 1149, 'en', 'Game Numerical Designer'),
('job', 1150, 'en', 'UX Designer'),
('job', 1151, 'en', 'User Research Manager'),
('job', 1152, 'en', 'User Research Director'),
('job', 1153, 'en', 'Senior Design Jobs'),
('job', 1154, 'en', 'Senior Design Jobs'),
('job', 1155, 'en', 'Design Manager'),
('job', 1156, 'en', 'Design Director'),
('job', 1157, 'en', 'Visual Design Manager'),
('job', 1158, 'en', 'Visual Design Director'),
('job', 1159, 'en', 'Interaction Design Manager'),
('job', 1160, 'en', 'Interaction Design Director'),
('job', 1161, 'en', 'Non-visual Design'),
('job', 1162, 'en', 'Exhibition Design'),
('job', 1163, 'en', 'Non-visual Design'),
('job', 1164, 'en', 'Fashion / Textile Design'),
('job', 1165, 'en', 'Industrial Design'),
('job', 1166, 'en', 'Cabinet Design'),
('job', 1167, 'en', 'Furniture Design'),
('job', 1168, 'en', 'Home Design'),
('job', 1169, 'en', 'Jewelry Design'),
('job', 1170, 'en', 'Interior Design'),
('job', 1171, 'en', 'Visual Merchandising'),
('job', 1172, 'en', 'Other Design Jobs'),
('job', 1173, 'en', 'Other Design Jobs'),
('job', 1174, 'en', 'Operations'),
('job', 1175, 'en', 'Operations'),
('job', 1176, 'en', 'Feed / Data Analysis'),
('job', 1177, 'en', 'Livestream Operations'),
('job', 1178, 'en', 'Vehicle Operations'),
('job', 1179, 'en', 'Cross-border E-commerce Ops'),
('job', 1180, 'en', 'Online Store Manager'),
('job', 1182, 'en', 'User Operations'),
('job', 1183, 'en', 'Product Operations'),
('job', 1184, 'en', 'Data Operations'),
('job', 1185, 'en', 'Content Operations'),
('job', 1186, 'en', 'Event Operations'),
('job', 1187, 'en', 'Merchant Operations'),
('job', 1188, 'en', 'Category Operations'),
('job', 1189, 'en', 'Game Operations'),
('job', 1190, 'en', 'Online Promotion'),
('job', 1191, 'en', 'Website Operations'),
('job', 1192, 'en', 'New Media Operations'),
('job', 1193, 'en', 'Community Operations'),
('job', 1197, 'en', 'Offline Expansion'),
('job', 1198, 'en', 'E-commerce Operations'),
('job', 1199, 'en', 'Operations Assistant / Specialist'),
('job', 1200, 'en', 'Content Moderator'),
('job', 1201, 'en', 'Sales Operations'),
('job', 1202, 'en', 'Editor'),
('job', 1203, 'en', 'Editor'),
('job', 1204, 'en', 'Deputy Editor-in-Chief'),
('job', 1205, 'en', 'Content Editor'),
('job', 1206, 'en', 'Copy Planning'),
('job', 1207, 'en', 'Web Editor'),
('job', 1208, 'en', 'Journalist'),
('job', 1209, 'en', 'Reporter / Editor'),
('job', 1210, 'en', 'Customer Service'),
('job', 1211, 'en', 'Pre-sales Consulting'),
('job', 1212, 'en', 'After-sales Consulting'),
('job', 1213, 'en', 'Online Store Support'),
('job', 1214, 'en', 'Customer Service Manager'),
('job', 1215, 'en', 'Customer Service Specialist'),
('job', 1216, 'en', 'Customer Service Supervisor'),
('job', 1217, 'en', 'Phone Support'),
('job', 1218, 'en', 'Hotline / Call Center'),
('job', 1219, 'en', 'Senior Operations Jobs'),
('job', 1220, 'en', 'Senior Operations Jobs'),
('job', 1221, 'en', 'Editor-in-Chief'),
('job', 1222, 'en', 'Operations Director'),
('job', 1223, 'en', 'COO'),
('job', 1224, 'en', 'Customer Service Director'),
('job', 1225, 'en', 'Operations Manager'),
('job', 1226, 'en', 'Other Operations Jobs'),
('job', 1227, 'en', 'Other Operations Jobs'),
('job', 1228, 'en', 'Marketing'),
('job', 1229, 'en', 'Government Affairs'),
('job', 1230, 'en', 'Policy Research'),
('job', 1231, 'en', 'Party Building'),
('job', 1232, 'en', 'Government Relations'),
('job', 1233, 'en', 'Marketing'),
('job', 1234, 'en', 'Site Development'),
('job', 1235, 'en', 'Game Promotion'),
('job', 1236, 'en', 'Marketing'),
('job', 1237, 'en', 'Marketing Planning'),
('job', 1238, 'en', 'Marketing Consultant'),
('job', 1239, 'en', 'Marketing Promotion'),
('job', 1240, 'en', 'SEO'),
('job', 1241, 'en', 'SEM'),
('job', 1242, 'en', 'Business Channels'),
('job', 1243, 'en', 'Business Data Analysis'),
('job', 1244, 'en', 'Event Planning'),
('job', 1245, 'en', 'Online Marketing'),
('job', 1246, 'en', 'Overseas Markets'),
('job', 1247, 'en', 'App Promotion'),
('job', 1248, 'en', 'PR & Media'),
('job', 1249, 'en', 'PR & Media'),
('job', 1250, 'en', 'Media Manager'),
('job', 1251, 'en', 'Advertising Coordinator'),
('job', 1252, 'en', 'Brand PR'),
('job', 1253, 'en', 'Media Specialist'),
('job', 1254, 'en', 'Event Planning & Execution'),
('job', 1255, 'en', 'Media Planning'),
('job', 1256, 'en', 'Conferences & Exhibitions'),
('job', 1257, 'en', 'Conferences & Exhibitions'),
('job', 1258, 'en', 'Event Sales'),
('job', 1259, 'en', 'Event Planning'),
('job', 1260, 'en', 'Event Execution'),
('job', 1261, 'en', 'Exhibition Sales'),
('job', 1262, 'en', 'Exhibition Planning'),
('job', 1263, 'en', 'Exhibition Execution'),
('job', 1264, 'en', 'Advertising'),
('job', 1265, 'en', 'Advertising / Exhibition Project Manager'),
('job', 1266, 'en', 'Advertising'),
('job', 1267, 'en', 'Advertising Creative'),
('job', 1268, 'en', 'Art Director'),
('job', 1269, 'en', 'Advertising Designer'),
('job', 1270, 'en', 'Planning Manager'),
('job', 1271, 'en', 'Copywriting'),
('job', 1272, 'en', 'Advertising Production'),
('job', 1273, 'en', 'Media Buying'),
('job', 1274, 'en', 'Media Partnerships'),
('job', 1275, 'en', 'Media Consultant'),
('job', 1276, 'en', 'Advertising Review'),
('job', 1277, 'en', 'Senior Marketing Jobs'),
('job', 1278, 'en', 'Senior Marketing Jobs'),
('job', 1279, 'en', 'Marketing Director'),
('job', 1280, 'en', 'CMO'),
('job', 1281, 'en', 'PR Director'),
('job', 1282, 'en', 'Media Director'),
('job', 1283, 'en', 'Creative Director'),
('job', 1284, 'en', 'Other Marketing Jobs'),
('job', 1285, 'en', 'Other Marketing Jobs'),
('job', 1286, 'en', 'HR / Admin / Finance'),
('job', 1287, 'en', 'Human Resources'),
('job', 1288, 'en', 'HR Supervisor'),
('job', 1289, 'en', 'Recruitment'),
('job', 1290, 'en', 'HRBP'),
('job', 1291, 'en', 'HR Specialist / Assistant'),
('job', 1292, 'en', 'Training'),
('job', 1293, 'en', 'Compensation & Benefits'),
('job', 1294, 'en', 'Performance Appraisal'),
('job', 1295, 'en', 'HR Manager'),
('job', 1296, 'en', 'VP of HR / CHO'),
('job', 1297, 'en', 'HR Director'),
('job', 1298, 'en', 'Employee Relations'),
('job', 1299, 'en', 'Organization Development'),
('job', 1300, 'en', 'Administration'),
('job', 1301, 'en', 'Admin Specialist / Assistant'),
('job', 1302, 'en', 'Receptionist'),
('job', 1303, 'en', 'Admin Supervisor'),
('job', 1304, 'en', 'Manager Assistant'),
('job', 1305, 'en', 'Office Clerk'),
('job', 1306, 'en', 'Company Driver'),
('job', 1307, 'en', 'Admin Manager'),
('job', 1308, 'en', 'Admin Director'),
('job', 1309, 'en', 'Finance'),
('job', 1310, 'en', 'Cost Accounting'),
('job', 1311, 'en', 'Finance'),
('job', 1312, 'en', 'Accountant'),
('job', 1313, 'en', 'Cashier (Finance)'),
('job', 1314, 'en', 'Financial Consultant'),
('job', 1315, 'en', 'Settlement'),
('job', 1316, 'en', 'Tax'),
('job', 1317, 'en', 'Audit'),
('job', 1318, 'en', 'Risk Control'),
('job', 1319, 'en', 'Finance Manager'),
('job', 1320, 'en', 'CFO'),
('job', 1321, 'en', 'Finance Director'),
('job', 1322, 'en', 'Finance Supervisor'),
('job', 1323, 'en', 'Legal Affairs'),
('job', 1324, 'en', 'Legal Specialist / Assistant'),
('job', 1325, 'en', 'Lawyer'),
('job', 1326, 'en', 'Legal Counsel'),
('job', 1327, 'en', 'Legal Supervisor'),
('job', 1328, 'en', 'Legal Manager'),
('job', 1329, 'en', 'Legal Director'),
('job', 1330, 'en', 'Other Functional Jobs'),
('job', 1331, 'en', 'Other Functional Jobs'),
('job', 1332, 'en', 'Senior Management'),
('job', 1333, 'en', 'Senior Management Jobs'),
('job', 1334, 'en', 'Senior Management Jobs'),
('job', 1335, 'en', 'CEO / General Manager'),
('job', 1336, 'en', 'Vice President'),
('job', 1337, 'en', 'CEO / Chairman Assistant'),
('job', 1338, 'en', 'Partner'),
('job', 1339, 'en', 'Co-founder'),
('job', 1340, 'en', 'Board Secretary'),
('job', 1341, 'en', 'Sales'),
('job', 1342, 'en', 'Sales'),
('job', 1343, 'en', 'Sales Manager'),
('job', 1344, 'en', 'Sales Specialist'),
('job', 1345, 'en', 'Sales Manager'),
('job', 1346, 'en', 'Account Representative'),
('job', 1347, 'en', 'Key Account Representative'),
('job', 1348, 'en', 'BD Manager'),
('job', 1349, 'en', 'Business Channels'),
('job', 1350, 'en', 'Channel Sales'),
('job', 1351, 'en', 'Distributor Sales'),
('job', 1352, 'en', 'Sales Assistant'),
('job', 1353, 'en', 'Telemarketing'),
('job', 1354, 'en', 'Sales Consultant'),
('job', 1355, 'en', 'Merchandiser'),
('job', 1356, 'en', 'Advertising Sales'),
('job', 1357, 'en', 'Online Marketing'),
('job', 1358, 'en', 'Marketing Supervisor'),
('job', 1359, 'en', 'Sales Engineer'),
('job', 1360, 'en', 'Account Manager'),
('job', 1361, 'en', 'Sales Management'),
('job', 1362, 'en', 'Sales Supervisor'),
('job', 1363, 'en', 'Sales Director'),
('job', 1364, 'en', 'Business Director'),
('job', 1365, 'en', 'Regional Director'),
('job', 1366, 'en', 'City Manager'),
('job', 1367, 'en', 'VP of Sales'),
('job', 1368, 'en', 'Team Manager'),
('job', 1370, 'en', 'Other Sales Jobs'),
('job', 1371, 'en', 'Other Sales Jobs'),
('job', 1372, 'en', 'Media'),
('job', 1373, 'en', 'Editing / Writing / Publishing'),
('job', 1374, 'en', 'Typesetting'),
('job', 1375, 'en', 'Editing / Writing / Publishing'),
('job', 1376, 'en', 'Journalist'),
('job', 1377, 'en', 'Editor'),
('job', 1378, 'en', 'Reporter / Editor'),
('job', 1379, 'en', 'Copywriter'),
('job', 1380, 'en', 'Publishing'),
('job', 1381, 'en', 'Proofreading / Data Entry'),
('job', 1382, 'en', 'Editor-in-Chief'),
('job', 1383, 'en', 'We-media'),
('job', 1384, 'en', 'PR & Media'),
('job', 1385, 'en', 'PR & Media'),
('job', 1386, 'en', 'Media Manager'),
('job', 1387, 'en', 'Media Specialist'),
('job', 1388, 'en', 'Advertising Coordinator'),
('job', 1389, 'en', 'Brand PR'),
('job', 1390, 'en', 'Event Planning & Execution'),
('job', 1391, 'en', 'Media Planning'),
('job', 1392, 'en', 'Conferences & Exhibitions'),
('job', 1393, 'en', 'Conferences & Exhibitions'),
('job', 1394, 'en', 'Event Sales'),
('job', 1395, 'en', 'Event Planning'),
('job', 1396, 'en', 'Event Execution'),
('job', 1397, 'en', 'Exhibition Sales'),
('job', 1398, 'en', 'Exhibition Planning'),
('job', 1399, 'en', 'Exhibition Execution'),
('job', 1400, 'en', 'Advertising'),
('job', 1401, 'en', 'Advertising / Exhibition Project Manager'),
('job', 1402, 'en', 'Advertising'),
('job', 1403, 'en', 'Advertising Creative'),
('job', 1404, 'en', 'Art Director'),
('job', 1405, 'en', 'Advertising Designer'),
('job', 1406, 'en', 'Planning Manager'),
('job', 1407, 'en', 'Copywriting'),
('job', 1408, 'en', 'Advertising Production'),
('job', 1409, 'en', 'Media Buying'),
('job', 1410, 'en', 'Media Partnerships'),
('job', 1411, 'en', 'Media Consultant'),
('job', 1412, 'en', 'Advertising Review'),
('job', 1413, 'en', 'Film & TV Media'),
('job', 1414, 'en', 'Host / DJ'),
('job', 1415, 'en', 'Streamer Assistant'),
('job', 1416, 'en', 'Lighting Technician'),
('job', 1417, 'en', 'Video Editor'),
('job', 1418, 'en', 'VFX'),
('job', 1419, 'en', 'Film & TV Media'),
('job', 1420, 'en', 'Artist Assistant'),
('job', 1421, 'en', 'Line Producer'),
('job', 1422, 'en', 'Executive Producer'),
('job', 1423, 'en', 'Director'),
('job', 1424, 'en', 'Photography / Videography'),
('job', 1425, 'en', 'Video Editor'),
('job', 1426, 'en', 'Audio Editor'),
('job', 1427, 'en', 'Agent'),
('job', 1428, 'en', 'Post-production'),
('job', 1429, 'en', 'Film & TV Production'),
('job', 1430, 'en', 'Film & TV Distribution'),
('job', 1431, 'en', 'Film & TV Planning'),
('job', 1432, 'en', 'Livestreamer'),
('job', 1433, 'en', 'Actor / Voice Actor / Model'),
('job', 1434, 'en', 'Makeup / Styling / Costume'),
('job', 1435, 'en', 'Projection Management'),
('job', 1436, 'en', 'Recording / Sound Effects'),
('job', 1437, 'en', 'Producer'),
('job', 1438, 'en', 'Screenwriter'),
('job', 1439, 'en', 'Other Media Jobs'),
('job', 1440, 'en', 'Other Media Jobs'),
('job', 1441, 'en', 'Finance'),
('job', 1442, 'en', 'Investment & Financing'),
('job', 1443, 'en', 'Investment & Financing'),
('job', 1444, 'en', 'Investment Manager'),
('job', 1445, 'en', 'Industry Research'),
('job', 1446, 'en', 'Asset Management'),
('job', 1447, 'en', 'Investment Director'),
('job', 1448, 'en', 'VP of Investment'),
('job', 1449, 'en', 'Investment Partner'),
('job', 1450, 'en', 'Fundraising'),
('job', 1451, 'en', 'M&A'),
('job', 1452, 'en', 'Post-investment Management'),
('job', 1453, 'en', 'Investment Assistant'),
('job', 1454, 'en', 'Other Investment Jobs'),
('job', 1455, 'en', 'Investment Advisor'),
('job', 1456, 'en', 'Risk Control'),
('job', 1457, 'en', 'Risk Control'),
('job', 1458, 'en', 'Lawyer'),
('job', 1459, 'en', 'Credit Rating'),
('job', 1460, 'en', 'Compliance & Audit'),
('job', 1461, 'en', 'Tax Audit'),
('job', 1462, 'en', 'Audit'),
('job', 1463, 'en', 'Legal Affairs'),
('job', 1464, 'en', 'Accountant'),
('job', 1465, 'en', 'Clearing'),
('job', 1466, 'en', 'Banking'),
('job', 1467, 'en', 'Banking'),
('job', 1468, 'en', 'Credit Card Sales'),
('job', 1469, 'en', 'Analyst'),
('job', 1470, 'en', 'Bank Teller'),
('job', 1471, 'en', 'Business Channels'),
('job', 1472, 'en', 'Lobby Manager'),
('job', 1473, 'en', 'Financial Advisor'),
('job', 1474, 'en', 'Account Manager'),
('job', 1475, 'en', 'Credit Management'),
('job', 1476, 'en', 'Risk Control'),
('job', 1477, 'en', 'Internet Finance'),
('job', 1478, 'en', 'Financial Product Manager'),
('job', 1479, 'en', 'Risk Control'),
('job', 1480, 'en', 'Debt Collector'),
('job', 1481, 'en', 'Analyst'),
('job', 1482, 'en', 'Investment Manager'),
('job', 1483, 'en', 'Trader'),
('job', 1484, 'en', 'Financial Advisor'),
('job', 1485, 'en', 'Compliance & Audit'),
('job', 1486, 'en', 'Audit'),
('job', 1487, 'en', 'Clearing'),
('job', 1488, 'en', 'Insurance'),
('job', 1489, 'en', 'Insurance Agent'),
('job', 1490, 'en', 'Actuary'),
('job', 1491, 'en', 'Insurance Claims'),
('job', 1492, 'en', 'Securities'),
('job', 1493, 'en', 'Securities Broker'),
('job', 1494, 'en', 'Securities Analyst'),
('job', 1495, 'en', 'Other Finance Jobs'),
('job', 1496, 'en', 'Other Finance Jobs'),
('job', 1497, 'en', 'Education / Training'),
('job', 1498, 'en', 'Education Product R&D'),
('job', 1499, 'en', 'Education Product R&D'),
('job', 1500, 'en', 'Curriculum Design'),
('job', 1501, 'en', 'Course Editor'),
('job', 1502, 'en', 'Teacher'),
('job', 1503, 'en', 'Training Research'),
('job', 1504, 'en', 'Trainer'),
('job', 1505, 'en', 'Training Planning'),
('job', 1506, 'en', 'Other Education Product R&D Jobs'),
('job', 1507, 'en', 'Education Administration'),
('job', 1508, 'en', 'Kindergarten Principal'),
('job', 1509, 'en', 'Education Administration'),
('job', 1510, 'en', 'School Principal'),
('job', 1511, 'en', 'Academic Affairs'),
('job', 1512, 'en', 'Teaching Management'),
('job', 1513, 'en', 'Homeroom Teacher / Counselor'),
('job', 1514, 'en', 'Teacher'),
('job', 1515, 'en', 'Japanese Teacher'),
('job', 1516, 'en', 'Other Foreign Language Teachers'),
('job', 1517, 'en', 'Chinese Teacher'),
('job', 1518, 'en', 'Math Teacher'),
('job', 1519, 'en', 'Physics Teacher'),
('job', 1520, 'en', 'Chemistry Teacher'),
('job', 1521, 'en', 'Biology Teacher'),
('job', 1522, 'en', 'Teacher'),
('job', 1523, 'en', 'Teaching Assistant'),
('job', 1524, 'en', 'High School Teacher'),
('job', 1525, 'en', 'Middle School Teacher'),
('job', 1526, 'en', 'Primary School Teacher'),
('job', 1527, 'en', 'Preschool Teacher'),
('job', 1528, 'en', 'Science Teacher'),
('job', 1529, 'en', 'Liberal Arts Teacher'),
('job', 1530, 'en', 'English Teacher'),
('job', 1531, 'en', 'Music Teacher'),
('job', 1532, 'en', 'Art Teacher'),
('job', 1533, 'en', 'PE Teacher'),
('job', 1534, 'en', 'Career Teacher'),
('job', 1535, 'en', 'IT Training'),
('job', 1536, 'en', 'IT Training'),
('job', 1537, 'en', 'Java Trainer'),
('job', 1538, 'en', 'Android Trainer'),
('job', 1539, 'en', 'iOS Trainer'),
('job', 1540, 'en', 'PHP Trainer'),
('job', 1541, 'en', '.NET Trainer'),
('job', 1542, 'en', 'C++ Trainer'),
('job', 1543, 'en', 'Unity'),
('job', 1544, 'en', '3D Trainer'),
('job', 1545, 'en', 'Web Frontend Trainer'),
('job', 1546, 'en', 'Software Testing Trainer'),
('job', 1547, 'en', 'Animation Trainer'),
('job', 1548, 'en', 'UI Design Trainer'),
('job', 1549, 'en', 'Vocational Training'),
('job', 1550, 'en', 'Accounting Trainer'),
('job', 1551, 'en', 'HR Trainer'),
('job', 1552, 'en', 'Trainer'),
('job', 1553, 'en', 'Outdoor Training'),
('job', 1554, 'en', 'Admissions'),
('job', 1555, 'en', 'Course Consultant'),
('job', 1556, 'en', 'Admissions Consultant'),
('job', 1557, 'en', 'Study Abroad Consultant'),
('job', 1558, 'en', 'Specialty Training'),
('job', 1559, 'en', 'Martial Arts Coach'),
('job', 1560, 'en', 'Roller Skating Coach'),
('job', 1561, 'en', 'Performing Arts Teacher'),
('job', 1562, 'en', 'Robotics Teacher'),
('job', 1563, 'en', 'Calligraphy Teacher'),
('job', 1564, 'en', 'Piano Teacher'),
('job', 1565, 'en', 'Guitar Teacher'),
('job', 1566, 'en', 'Guzheng Teacher'),
('job', 1567, 'en', 'Broadcasting Teacher'),
('job', 1568, 'en', 'LEGO Teacher'),
('job', 1569, 'en', 'Coach'),
('job', 1570, 'en', 'Dance Coach'),
('job', 1571, 'en', 'Yoga Instructor'),
('job', 1572, 'en', 'Weight-loss Consultant'),
('job', 1573, 'en', 'Swimming Coach'),
('job', 1574, 'en', 'Fitness Trainer'),
('job', 1575, 'en', 'Basketball / Badminton Coach'),
('job', 1576, 'en', 'Taekwondo Coach'),
('job', 1577, 'en', 'Other Education / Training Jobs'),
('job', 1578, 'en', 'Other Education / Training Jobs'),
('job', 1579, 'en', 'Healthcare'),
('job', 1580, 'en', 'Clinical Trials'),
('job', 1581, 'en', 'Clinical Project Manager'),
('job', 1582, 'en', 'Clinical Research'),
('job', 1583, 'en', 'Clinical Coordinator'),
('job', 1584, 'en', 'Clinical Data Analysis'),
('job', 1585, 'en', 'Medical Director'),
('job', 1586, 'en', 'Doctor / Medical Technician'),
('job', 1587, 'en', 'Physician Assistant'),
('job', 1588, 'en', 'Medical Imaging'),
('job', 1589, 'en', 'Ultrasound Physician'),
('job', 1590, 'en', 'TCM Doctor'),
('job', 1591, 'en', 'Physician'),
('job', 1592, 'en', 'Psychiatrist'),
('job', 1593, 'en', 'Pharmacist'),
('job', 1594, 'en', 'Dentist'),
('job', 1595, 'en', 'Rehabilitation Therapist'),
('job', 1596, 'en', 'Optometrist'),
('job', 1597, 'en', 'Radiologist'),
('job', 1598, 'en', 'Laboratory Physician'),
('job', 1599, 'en', 'Other Physician Jobs'),
('job', 1600, 'en', 'Nurse / Nursing'),
('job', 1601, 'en', 'Head Nurse'),
('job', 1602, 'en', 'Nurse / Nursing'),
('job', 1603, 'en', 'Hospital Guide'),
('job', 1604, 'en', 'Health & Cosmetic Medicine'),
('job', 1605, 'en', 'Health & Cosmetic Medicine'),
('job', 1606, 'en', 'Nutritionist'),
('job', 1607, 'en', 'Plastic Surgeon'),
('job', 1608, 'en', 'Physiotherapist'),
('job', 1609, 'en', 'Acupuncture & Massage'),
('job', 1610, 'en', 'Biopharmaceuticals'),
('job', 1611, 'en', 'Pharmaceutical Project Manager'),
('job', 1612, 'en', 'Biopharmaceuticals'),
('job', 1613, 'en', 'Drug Registration'),
('job', 1614, 'en', 'Drug Manufacturing'),
('job', 1615, 'en', 'Medical Director'),
('job', 1616, 'en', 'Pharmaceutical R&D'),
('job', 1617, 'en', 'Medical Devices'),
('job', 1618, 'en', 'Medical Device Registration'),
('job', 1619, 'en', 'Medical Device Production / QA'),
('job', 1620, 'en', 'Medical Device R&D'),
('job', 1621, 'en', 'Pharmacy'),
('job', 1622, 'en', 'Pharmacy Manager'),
('job', 1623, 'en', 'Licensed Pharmacist'),
('job', 1624, 'en', 'Pharmacy Clerk'),
('job', 1625, 'en', 'Medical Marketing / Media'),
('job', 1626, 'en', 'Medical Marketing / Media'),
('job', 1627, 'en', 'Medical Device Sales'),
('job', 1628, 'en', 'Medical Editor'),
('job', 1629, 'en', 'Pharmacy Editor'),
('job', 1630, 'en', 'Pharmaceutical Sales Rep'),
('job', 1631, 'en', 'Health Consultant'),
('job', 1632, 'en', 'Medical Aesthetics Consultant'),
('job', 1633, 'en', 'Other Healthcare Jobs'),
('job', 1634, 'en', 'Other Healthcare Jobs'),
('job', 1635, 'en', 'Procurement / Trade'),
('job', 1636, 'en', 'Procurement'),
('job', 1637, 'en', 'Supplier Quality Engineer'),
('job', 1638, 'en', 'Procurement'),
('job', 1639, 'en', 'Procurement Director'),
('job', 1640, 'en', 'Procurement Manager'),
('job', 1641, 'en', 'Procurement Specialist'),
('job', 1642, 'en', 'Buyer'),
('job', 1643, 'en', 'Procurement Engineer'),
('job', 1644, 'en', 'Procurement Supervisor'),
('job', 1645, 'en', 'Procurement Assistant'),
('job', 1646, 'en', 'Import / Export'),
('job', 1647, 'en', 'Import / Export'),
('job', 1648, 'en', 'Foreign Trade Manager'),
('job', 1649, 'en', 'Foreign Trade Specialist'),
('job', 1650, 'en', 'Foreign Trade Sales'),
('job', 1651, 'en', 'Trade Merchandiser'),
('job', 1652, 'en', 'Other Procurement / Trade Jobs'),
('job', 1653, 'en', 'Other Procurement / Trade Jobs'),
('job', 1654, 'en', 'Supply Chain / Logistics'),
('job', 1655, 'en', 'Logistics'),
('job', 1656, 'en', 'Supply Chain Specialist'),
('job', 1657, 'en', 'Supply Chain Manager'),
('job', 1658, 'en', 'Logistics Specialist'),
('job', 1659, 'en', 'Logistics Manager'),
('job', 1660, 'en', 'Logistics Operations'),
('job', 1661, 'en', 'Logistics Merchandiser'),
('job', 1662, 'en', 'Trade Merchandiser'),
('job', 1663, 'en', 'Warehouse Dispatch'),
('job', 1664, 'en', 'Logistics / Warehouse Project Manager'),
('job', 1665, 'en', 'Transportation Manager'),
('job', 1666, 'en', 'Freight Forwarding Specialist'),
('job', 1667, 'en', 'Freight Forwarding Manager'),
('job', 1668, 'en', 'Sea / Air / Land Freight Ops'),
('job', 1669, 'en', 'Customs Declarant'),
('job', 1670, 'en', 'Inspection Clerk'),
('job', 1671, 'en', 'Verification Clerk'),
('job', 1672, 'en', 'Documentation Clerk'),
('job', 1673, 'en', 'Warehousing'),
('job', 1674, 'en', 'Warehouse Materials Manager'),
('job', 1675, 'en', 'Warehouse Materials Specialist'),
('job', 1676, 'en', 'Warehouse Manager'),
('job', 1677, 'en', 'Warehouse Clerk'),
('job', 1678, 'en', 'Picking / Packing / Shipping'),
('job', 1679, 'en', 'Transportation'),
('job', 1680, 'en', 'Truck Driver'),
('job', 1682, 'en', 'Delivery Courier'),
('job', 1683, 'en', 'Courier'),
('job', 1684, 'en', 'Senior Supply Chain Jobs'),
('job', 1685, 'en', 'Supply Chain Director'),
('job', 1686, 'en', 'Logistics Director'),
('job', 1687, 'en', 'Senior Supply Chain Jobs'),
('job', 1688, 'en', 'Other Supply Chain Jobs'),
('job', 1689, 'en', 'Other Supply Chain Jobs'),
('job', 1690, 'en', 'Real Estate / Construction'),
('job', 1691, 'en', 'Real Estate Development'),
('job', 1692, 'en', 'Real Estate Development'),
('job', 1693, 'en', 'Real Estate Planning'),
('job', 1694, 'en', 'Real Estate Project Management'),
('job', 1695, 'en', 'Real Estate Tendering'),
('job', 1696, 'en', 'Interior Design & Municipal Construction'),
('job', 1697, 'en', 'Low-voltage Engineer'),
('job', 1698, 'en', 'Plumbing Engineer'),
('job', 1699, 'en', 'HVAC Engineer'),
('job', 1700, 'en', 'Curtain Wall Engineer'),
('job', 1701, 'en', 'Soft Furnishings Designer'),
('job', 1702, 'en', 'Construction Worker'),
('job', 1703, 'en', 'Surveying'),
('job', 1704, 'en', 'Materials Clerk'),
('job', 1705, 'en', 'BIM Engineer'),
('job', 1706, 'en', 'Renovation Project Manager'),
('job', 1707, 'en', 'Interior Design & Municipal Construction'),
('job', 1708, 'en', 'Senior Construction Engineer'),
('job', 1709, 'en', 'Architect Engineer'),
('job', 1710, 'en', 'Architect'),
('job', 1711, 'en', 'Civil / Structural Engineer'),
('job', 1712, 'en', 'Interior Design'),
('job', 1713, 'en', 'Landscape Design'),
('job', 1714, 'en', 'Urban Planning'),
('job', 1715, 'en', 'Construction Supervisor'),
('job', 1716, 'en', 'Quantity Surveying'),
('job', 1717, 'en', 'Cost Estimation'),
('job', 1718, 'en', 'Engineering Documentation'),
('job', 1719, 'en', 'Construction Site Management'),
('job', 1720, 'en', 'Landscape Design'),
('job', 1721, 'en', 'Real Estate Brokerage'),
('job', 1722, 'en', 'Real Estate Broker'),
('job', 1723, 'en', 'Property Consultant'),
('job', 1724, 'en', 'Property Appraisal'),
('job', 1725, 'en', 'Real Estate Agent'),
('job', 1726, 'en', 'Property Management'),
('job', 1727, 'en', 'Property Maintenance'),
('job', 1728, 'en', 'Gardener'),
('job', 1729, 'en', 'Property Butler'),
('job', 1730, 'en', 'Property Manager'),
('job', 1731, 'en', 'Property Rental Sales'),
('job', 1732, 'en', 'Property Leasing Management'),
('job', 1733, 'en', 'Cleaner'),
('job', 1734, 'en', 'Senior Real Estate Jobs'),
('job', 1735, 'en', 'Senior Real Estate Jobs'),
('job', 1736, 'en', 'Real Estate Project Director'),
('job', 1737, 'en', 'Real Estate Planning Director'),
('job', 1738, 'en', 'Real Estate Tendering Director'),
('job', 1739, 'en', 'Property Director'),
('job', 1740, 'en', 'Real Estate Sales Director'),
('job', 1741, 'en', 'Other Real Estate Jobs'),
('job', 1742, 'en', 'Other Real Estate Jobs'),
('job', 1743, 'en', 'Consulting / Translation / Legal'),
('job', 1744, 'en', 'Consulting / Research'),
('job', 1745, 'en', 'IP / Patent / Trademark Agent'),
('job', 1746, 'en', 'Psychological Counseling'),
('job', 1747, 'en', 'Matchmaking Consultant'),
('job', 1748, 'en', 'Market Research'),
('job', 1749, 'en', 'Management Consulting'),
('job', 1750, 'en', 'Consulting Director'),
('job', 1751, 'en', 'Data Analyst'),
('job', 1752, 'en', 'Consulting Manager'),
('job', 1753, 'en', 'Finance Consultant'),
('job', 1754, 'en', 'IT Consultant'),
('job', 1755, 'en', 'HR Consultant'),
('job', 1756, 'en', 'Consulting Project Management'),
('job', 1757, 'en', 'Strategy Consulting'),
('job', 1758, 'en', 'Headhunter'),
('job', 1759, 'en', 'Market Research'),
('job', 1760, 'en', 'Other Consultants'),
('job', 1761, 'en', 'Lawyer'),
('job', 1762, 'en', 'IP Lawyer'),
('job', 1763, 'en', 'Legal Assistant'),
('job', 1764, 'en', 'Patent Attorney'),
('job', 1765, 'en', 'Law Firm Attorney'),
('job', 1766, 'en', 'Corporate Legal Counsel'),
('job', 1767, 'en', 'Translation'),
('job', 1768, 'en', 'English Translator'),
('job', 1769, 'en', 'Japanese Translator'),
('job', 1770, 'en', 'Korean Translator'),
('job', 1771, 'en', 'French Translator'),
('job', 1772, 'en', 'Simultaneous Interpreter'),
('job', 1773, 'en', 'German Translator'),
('job', 1774, 'en', 'Russian Translator'),
('job', 1775, 'en', 'Spanish Translator'),
('job', 1776, 'en', 'Other Language Translators'),
('job', 1777, 'en', 'Other Consulting Jobs'),
('job', 1778, 'en', 'Other Consulting / Translation Jobs'),
('job', 1779, 'en', 'Tourism'),
('job', 1780, 'en', 'Tourism Services'),
('job', 1781, 'en', 'Docent'),
('job', 1782, 'en', 'Tourism Services'),
('job', 1783, 'en', 'Tour Operator'),
('job', 1784, 'en', 'Visa Services'),
('job', 1785, 'en', 'Travel Consultant'),
('job', 1786, 'en', 'Tour Guide'),
('job', 1787, 'en', 'Ticketing'),
('job', 1788, 'en', 'Tourism Product Development'),
('job', 1789, 'en', 'Tourism Product Development'),
('job', 1790, 'en', 'Tourism Product Manager'),
('job', 1791, 'en', 'Tourism Planner'),
('job', 1792, 'en', 'Other Tourism Jobs'),
('job', 1793, 'en', 'Other Tourism Jobs'),
('job', 1794, 'en', 'Services'),
('job', 1795, 'en', 'Food & Beverage'),
('job', 1796, 'en', 'Kitchen'),
('job', 1797, 'en', 'Prep Cook'),
('job', 1798, 'en', 'Tea Artist'),
('job', 1799, 'en', 'Pastry Chef'),
('job', 1800, 'en', 'F&B Apprentice'),
('job', 1801, 'en', 'Pastry / Noodle Chef'),
('job', 1802, 'en', 'Executive Chef'),
('job', 1803, 'en', 'Head Chef'),
('job', 1804, 'en', 'Food Runner'),
('job', 1805, 'en', 'Dishwasher'),
('job', 1806, 'en', 'Cold Dish Chef'),
('job', 1807, 'en', 'Chinese Cuisine Chef'),
('job', 1808, 'en', 'Western Cuisine Chef'),
('job', 1809, 'en', 'Japanese Cuisine Chef'),
('job', 1810, 'en', 'Barbecue Chef'),
('job', 1811, 'en', 'Cashier'),
('job', 1812, 'en', 'Waiter / Waitress'),
('job', 1813, 'en', 'Chef'),
('job', 1814, 'en', 'Barista'),
('job', 1815, 'en', 'Food Delivery'),
('job', 1816, 'en', 'Restaurant Manager'),
('job', 1817, 'en', 'Shift Leader'),
('job', 1818, 'en', 'Retail'),
('job', 1819, 'en', 'Store Supervisor'),
('job', 1820, 'en', 'Visual Merchandiser'),
('job', 1821, 'en', 'Stock Clerk'),
('job', 1822, 'en', 'Loss Prevention'),
('job', 1823, 'en', 'Store Manager'),
('job', 1824, 'en', 'Cashier'),
('job', 1825, 'en', 'Sales Associate'),
('job', 1826, 'en', 'Shop Assistant'),
('job', 1827, 'en', 'Store Manager'),
('job', 1828, 'en', 'Hotel'),
('job', 1829, 'en', 'Greeter'),
('job', 1830, 'en', 'Front Office Manager'),
('job', 1831, 'en', 'Housekeeping Manager'),
('job', 1832, 'en', 'Cashier'),
('job', 1833, 'en', 'Hotel Reception'),
('job', 1834, 'en', 'Room Attendant'),
('job', 1835, 'en', 'Hotel Manager'),
('job', 1836, 'en', 'Lobby Manager'),
('job', 1837, 'en', 'Beauty & Wellness'),
('job', 1838, 'en', 'Makeup Consultant'),
('job', 1839, 'en', 'Permanent Makeup Artist'),
('job', 1840, 'en', 'Body Care Specialist'),
('job', 1841, 'en', 'Hairdressing Apprentice'),
('job', 1842, 'en', 'Beauty Salon Manager'),
('job', 1843, 'en', 'Foot Therapist'),
('job', 1844, 'en', 'Masseur'),
('job', 1845, 'en', 'Hair Stylist'),
('job', 1846, 'en', 'Nail Technician'),
('job', 1847, 'en', 'Makeup Artist'),
('job', 1848, 'en', 'Hair Care Specialist'),
('job', 1849, 'en', 'Beautician / Consultant'),
('job', 1850, 'en', 'Sports & Fitness'),
('job', 1851, 'en', 'Membership Consultant'),
('job', 1852, 'en', 'Lifeguard'),
('job', 1853, 'en', 'Fitness'),
('job', 1854, 'en', 'Yoga Instructor'),
('job', 1855, 'en', 'Weight-loss Consultant'),
('job', 1856, 'en', 'Swimming Coach'),
('job', 1857, 'en', 'Body Shaping Coach'),
('job', 1858, 'en', 'Dance Coach'),
('job', 1859, 'en', 'Fitness Trainer'),
('job', 1860, 'en', 'Logistics Support'),
('job', 1861, 'en', 'Security Guard'),
('job', 1862, 'en', 'Cleaner'),
('job', 1863, 'en', 'Nanny'),
('job', 1864, 'en', 'Maternity Matron'),
('job', 1865, 'en', 'Infant Caregiver'),
('job', 1866, 'en', 'Caregiver'),
('job', 1867, 'en', 'Security Screener'),
('job', 1868, 'en', 'Phone Repair'),
('job', 1869, 'en', 'Appliance Repair'),
('job', 1870, 'en', 'Security Manager'),
('job', 1871, 'en', 'Postpartum Recovery Specialist'),
('job', 1872, 'en', 'Wedding / Floral'),
('job', 1873, 'en', 'Florist'),
('job', 1874, 'en', 'Wedding Planner'),
('job', 1875, 'en', 'Pet Services'),
('job', 1876, 'en', 'Pet Grooming'),
('job', 1877, 'en', 'Veterinarian'),
('job', 1878, 'en', 'Other Service Jobs'),
('job', 1879, 'en', 'Other Service Jobs'),
('job', 1880, 'en', 'Manufacturing'),
('job', 1881, 'en', 'Production Operations'),
('job', 1882, 'en', 'Plant Manager'),
('job', 1883, 'en', 'Production Director'),
('job', 1884, 'en', 'Production Manager / Workshop Supervisor'),
('job', 1885, 'en', 'Production Line Leader'),
('job', 1886, 'en', 'Production Worker'),
('job', 1887, 'en', 'Production Equipment Management'),
('job', 1888, 'en', 'Production Planning / MRP'),
('job', 1889, 'en', 'Production Merchandiser'),
('job', 1890, 'en', 'Quality & Safety'),
('job', 1891, 'en', 'QC Inspector'),
('job', 1892, 'en', 'Quality Management / Testing'),
('job', 1893, 'en', 'Reliability Engineer'),
('job', 1894, 'en', 'Failure Analyst'),
('job', 1895, 'en', 'Certification Engineer'),
('job', 1896, 'en', 'Systems Engineer (QMS)'),
('job', 1897, 'en', 'Auditor'),
('job', 1898, 'en', 'Safety Officer'),
('job', 1899, 'en', 'Automotive Quality Engineer'),
('job', 1900, 'en', 'New Energy'),
('job', 1901, 'en', 'Battery Engineer'),
('job', 1902, 'en', 'Motor Engineer'),
('job', 1903, 'en', 'Wiring Harness Design'),
('job', 1904, 'en', 'EV Charger Design'),
('job', 1905, 'en', 'Automotive Manufacturing'),
('job', 1906, 'en', 'Automotive Design'),
('job', 1907, 'en', 'Body / Styling Design'),
('job', 1908, 'en', 'Chassis Engineer'),
('job', 1909, 'en', 'Powertrain Engineer'),
('job', 1910, 'en', 'Automotive Electronics Engineer'),
('job', 1911, 'en', 'Auto Parts Design'),
('job', 1912, 'en', 'Automotive Project Management'),
('job', 1913, 'en', 'Interior & Exterior Design Engineer'),
('job', 1914, 'en', 'Final Assembly Engineer'),
('job', 1915, 'en', 'Auto Sales & Service'),
('job', 1916, 'en', 'Car Sales'),
('job', 1917, 'en', 'Auto Parts Sales'),
('job', 1918, 'en', 'Auto Service Advisor'),
('job', 1919, 'en', 'Auto Repair'),
('job', 1920, 'en', 'Auto Detailing'),
('job', 1921, 'en', 'Auto Claims Assessor'),
('job', 1922, 'en', 'Used Car Appraiser'),
('job', 1923, 'en', '4S Store / Service Station Manager'),
('job', 1924, 'en', 'Auto Modification Engineer'),
('job', 1925, 'en', 'Mechanical Design / Manufacturing'),
('job', 1926, 'en', 'Mechanical Design / Manufacturing'),
('job', 1927, 'en', 'Heat Transfer'),
('job', 1928, 'en', 'Lean Engineer'),
('job', 1929, 'en', 'Mechanical Engineer'),
('job', 1930, 'en', 'Mechanical Designer'),
('job', 1931, 'en', 'Mechanical Equipment Engineer'),
('job', 1932, 'en', 'Mechanical Maintenance'),
('job', 1933, 'en', 'Mechanical Drafting'),
('job', 1934, 'en', 'Mechanical Structure Engineer'),
('job', 1935, 'en', 'Industrial Engineer'),
('job', 1936, 'en', 'Process Engineer'),
('job', 1937, 'en', 'Materials Engineer'),
('job', 1938, 'en', 'Mechatronics Engineer'),
('job', 1939, 'en', 'CNC'),
('job', 1940, 'en', 'Stamping Engineer'),
('job', 1941, 'en', 'Fixture Engineer'),
('job', 1942, 'en', 'Mold Engineer'),
('job', 1943, 'en', 'Welding Engineer'),
('job', 1944, 'en', 'Injection Molding Engineer'),
('job', 1945, 'en', 'Casting / Forging Engineer'),
('job', 1946, 'en', 'Chemical Engineering'),
('job', 1947, 'en', 'Chemical Project Manager'),
('job', 1948, 'en', 'Chemical Engineer'),
('job', 1949, 'en', 'Lab Technician'),
('job', 1950, 'en', 'Chemical Analysis'),
('job', 1951, 'en', 'Coatings R&D'),
('job', 1952, 'en', 'Cosmetics R&D'),
('job', 1953, 'en', 'Food / Beverage R&D'),
('job', 1954, 'en', 'Apparel / Leather'),
('job', 1955, 'en', 'Fashion / Textile Design'),
('job', 1956, 'en', 'Fabric / Trims Development'),
('job', 1957, 'en', 'Sample / Pattern Making'),
('job', 1958, 'en', 'Apparel / Textile / Leather Merchandiser'),
('job', 1959, 'en', 'Technician / General Worker'),
('job', 1960, 'en', 'Sewer'),
('job', 1961, 'en', 'Porter'),
('job', 1962, 'en', 'Cutter'),
('job', 1963, 'en', 'Sample Garment Maker'),
('job', 1964, 'en', 'Mold Maker'),
('job', 1965, 'en', 'General Worker / Operator'),
('job', 1966, 'en', 'Forklift Operator'),
('job', 1967, 'en', 'Loader Operator'),
('job', 1968, 'en', 'Welder'),
('job', 1969, 'en', 'TIG Welder'),
('job', 1970, 'en', 'Electrician'),
('job', 1971, 'en', 'Carpenter'),
('job', 1972, 'en', 'Painter'),
('job', 1973, 'en', 'Lathe Operator'),
('job', 1974, 'en', 'Grinder'),
('job', 1975, 'en', 'Miller'),
('job', 1976, 'en', 'Fitter'),
('job', 1977, 'en', 'Driller'),
('job', 1978, 'en', 'Riveter'),
('job', 1979, 'en', 'Sheet Metal Worker'),
('job', 1980, 'en', 'Polisher'),
('job', 1981, 'en', 'Machine Repairer'),
('job', 1982, 'en', 'Bending Operator'),
('job', 1983, 'en', 'Electroplater'),
('job', 1984, 'en', 'Powder Coating Worker'),
('job', 1985, 'en', 'Injection Molding Worker'),
('job', 1986, 'en', 'Assembler'),
('job', 1987, 'en', 'Packer'),
('job', 1988, 'en', 'AC Technician'),
('job', 1989, 'en', 'Elevator Technician'),
('job', 1990, 'en', 'Boiler Operator'),
('job', 1991, 'en', 'Apprentice'),
('job', 1992, 'en', 'Other Manufacturing Jobs'),
('job', 1993, 'en', 'Other Manufacturing Jobs'),
('job', 1994, 'en', 'Fashion Design'),
('job', 1995, 'en', 'Cake Decorator'),
('job', 1996, 'en', 'Tea Drink Maker'),
('job', 1997, 'en', 'Clerk'),
('job', 1998, 'en', 'Production Clerk / Statistician'),
('job', 1999, 'en', 'Textile / Chemical Fiber'),
('job', 2000, 'en', 'Texturing Operator'),
('job', 2001, 'en', 'Loom Operator'),
('job', 2002, 'en', 'Winding Operator'),
('job', 2003, 'en', 'Spinning Operator'),
('job', 2004, 'en', 'Feeding Operator'),
('job', 2005, 'en', 'Carton Sealer'),
('job', 2006, 'en', 'Yarn Binding Operator'),
('job', 2007, 'en', 'Embroidery Worker'),
('job', 2008, 'en', 'Kindergarten Health Doctor'),
('job', 2009, 'en', 'Branch / Representative Office Head'),
('job', 2010, 'en', 'Regional Head (Multi-branch)'),
('job', 2011, 'en', 'Bartender'),
('job', 2012, 'en', 'Sales Control Clerk'),
('job', 2014, 'en', 'Patrol Officer'),
('job', 2015, 'en', 'Plumbing & Electrical Repair'),
('job', 2016, 'en', 'Childcare Worker'),
('job', 2017, 'en', 'Intern'),
('job', 2018, 'en', 'Management Trainee'),
('job', 2019, 'en', 'Temporary / Short-term Worker'),
('job', 2020, 'en', 'Project Director'),
('job', 2021, 'en', 'Driver'),
('job', 2022, 'en', 'Ride-hailing Driver'),
('job', 2023, 'en', 'Warehouse Keeper'),
('job', 2024, 'en', 'Driver'),
('job', 2025, 'en', 'Printer'),
('job', 2026, 'en', 'Press Operator'),
('job', 2027, 'en', 'Bookbinder'),
('job', 2028, 'en', 'Municipal/Utilities/Agriculture/Forestry/Animal Husbandry/Fishery'),
('job', 2029, 'en', 'Agriculture / Forestry'),
('job', 2030, 'en', 'Agriculture / Forestry Technician'),
('job', 2031, 'en', 'Seedling Planting / Maintenance'),
('job', 2032, 'en', 'Animal Husbandry / Fishery'),
('job', 2033, 'en', 'Breeder'),
('job', 2034, 'en', 'Livestock Veterinarian'),
('job', 2035, 'en', 'Livestock / Aquaculture Technician'),
('job', 2036, 'en', 'Other'),
('job', 2037, 'en', 'Transportation'),
('job', 2038, 'en', 'Audio-Visual Technology'),
('job', 2039, 'en', 'Biotechnology'),
('job', 2040, 'en', 'Surveying & Mapping'),
('job', 2041, 'en', 'Laser Technology'),
('job', 2042, 'en', 'Geological Exploration'),
('job', 2043, 'en', 'Mining & Metallurgy'),
('job', 2044, 'en', 'Environmental Engineering'),
('job', 2045, 'en', 'Municipal Management'),
('job', 2046, 'en', 'Urban Management'),
('job', 2047, 'en', 'Patrol Officer'),
('job', 2048, 'en', 'Auxiliary Police'),
('job', 2049, 'en', 'Community Service'),
('job', 2050, 'en', 'Energy'),
('job', 2051, 'en', 'Oil / Natural Gas'),
('job', 2052, 'en', 'HVAC'),
('job', 2053, 'en', 'Electric Power'),
('job', 2054, 'en', 'CIO'),
('job', 2055, 'en', 'Marine Machinery'),
('job', 2056, 'en', 'Textile Machinery'),
('job', 2057, 'en', 'Food Machinery'),
('job', 2058, 'en', 'Welding Machinery');
