-- Hierarchical region tree (countries / states / provinces / cities / districts).
-- Replaces the China-only static `dict.rs` tables; designed to scale globally.
-- See `crates/services/src/region_service.rs` for the runtime cache and pubsub-driven
-- multi-process refresh.

CREATE TABLE IF NOT EXISTS `phpyun_region` (
  `id`           BIGINT       NOT NULL AUTO_INCREMENT,
  `parent_id`    BIGINT       NULL COMMENT 'Self-ref; NULL for country-level rows',
  `country_code` CHAR(2)      NOT NULL COMMENT 'ISO 3166-1 alpha-2: CN/US/JP/...',
  `code`         VARCHAR(20)  NOT NULL COMMENT 'ISO 3166-2 + custom suffix; CN / CN-BJ / CN-BJ-CY / US-CA / US-CA-LA',
  `level`        TINYINT      NOT NULL COMMENT '0=country 1=state/province 2=city 3=district',
  `name`         VARCHAR(120) NOT NULL COMMENT 'Default name (English for global, zh-CN for China)',
  `continent`    CHAR(2)      NULL COMMENT 'AF/AN/AS/EU/NA/OC/SA (only for level=0)',
  `lat`          DECIMAL(10,6) NULL,
  `lng`          DECIMAL(10,6) NULL,
  `sort`         INT          NOT NULL DEFAULT 0,
  `status`       TINYINT      NOT NULL DEFAULT 0 COMMENT '0/1=active 2=deleted',
  `created_at`   BIGINT       NOT NULL DEFAULT 0,
  `updated_at`   BIGINT       NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_code` (`code`),
  KEY `idx_parent_sort` (`parent_id`, `sort`),
  KEY `idx_country_level` (`country_code`, `level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Hierarchical region tree (countries/states/cities/districts)';

-- ==================== Countries (level=0) ====================
INSERT INTO `phpyun_region` (id, parent_id, country_code, code, level, name, continent, sort, status, created_at, updated_at) VALUES
(1, NULL, 'AD', 'AD', 0, 'Andorra', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(2, NULL, 'AE', 'AE', 0, 'United Arab Emirates', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(3, NULL, 'AF', 'AF', 0, 'Afghanistan', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(4, NULL, 'AG', 'AG', 0, 'Antigua and Barbuda', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(5, NULL, 'AI', 'AI', 0, 'Anguilla', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(6, NULL, 'AL', 'AL', 0, 'Albania', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(7, NULL, 'AM', 'AM', 0, 'Armenia', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(8, NULL, 'AO', 'AO', 0, 'Angola', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(9, NULL, 'AQ', 'AQ', 0, 'Antarctica', 'AN', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(10, NULL, 'AR', 'AR', 0, 'Argentina', 'SA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(11, NULL, 'AS', 'AS', 0, 'American Samoa', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(12, NULL, 'AT', 'AT', 0, 'Austria', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(13, NULL, 'AU', 'AU', 0, 'Australia', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(14, NULL, 'AW', 'AW', 0, 'Aruba', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(15, NULL, 'AX', 'AX', 0, 'Åland', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(16, NULL, 'AZ', 'AZ', 0, 'Azerbaijan', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(17, NULL, 'BA', 'BA', 0, 'Bosnia and Herzegovina', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(18, NULL, 'BB', 'BB', 0, 'Barbados', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(19, NULL, 'BD', 'BD', 0, 'Bangladesh', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(20, NULL, 'BE', 'BE', 0, 'Belgium', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(21, NULL, 'BF', 'BF', 0, 'Burkina Faso', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(22, NULL, 'BG', 'BG', 0, 'Bulgaria', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(23, NULL, 'BH', 'BH', 0, 'Bahrain', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(24, NULL, 'BI', 'BI', 0, 'Burundi', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(25, NULL, 'BJ', 'BJ', 0, 'Benin', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(26, NULL, 'BL', 'BL', 0, 'Saint Barthélemy', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(27, NULL, 'BM', 'BM', 0, 'Bermuda', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(28, NULL, 'BN', 'BN', 0, 'Brunei', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(29, NULL, 'BO', 'BO', 0, 'Bolivia', 'SA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(30, NULL, 'BQ', 'BQ', 0, 'Bonaire, Sint Eustatius, and Saba', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(31, NULL, 'BR', 'BR', 0, 'Brazil', 'SA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(32, NULL, 'BS', 'BS', 0, 'Bahamas', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(33, NULL, 'BT', 'BT', 0, 'Bhutan', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(34, NULL, 'BV', 'BV', 0, 'Bouvet Island', 'AN', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(35, NULL, 'BW', 'BW', 0, 'Botswana', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(36, NULL, 'BY', 'BY', 0, 'Belarus', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(37, NULL, 'BZ', 'BZ', 0, 'Belize', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(38, NULL, 'CA', 'CA', 0, 'Canada', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(39, NULL, 'CC', 'CC', 0, 'Cocos (Keeling) Islands', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(40, NULL, 'CD', 'CD', 0, 'DR Congo', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(41, NULL, 'CF', 'CF', 0, 'Central African Republic', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(42, NULL, 'CG', 'CG', 0, 'Congo Republic', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(43, NULL, 'CH', 'CH', 0, 'Switzerland', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(44, NULL, 'CI', 'CI', 0, 'Ivory Coast', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(45, NULL, 'CK', 'CK', 0, 'Cook Islands', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(46, NULL, 'CL', 'CL', 0, 'Chile', 'SA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(47, NULL, 'CM', 'CM', 0, 'Cameroon', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(48, NULL, 'CN', 'CN', 0, 'China', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(49, NULL, 'CO', 'CO', 0, 'Colombia', 'SA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(50, NULL, 'CR', 'CR', 0, 'Costa Rica', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(51, NULL, 'CU', 'CU', 0, 'Cuba', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(52, NULL, 'CV', 'CV', 0, 'Cabo Verde', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(53, NULL, 'CW', 'CW', 0, 'Curaçao', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(54, NULL, 'CX', 'CX', 0, 'Christmas Island', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(55, NULL, 'CY', 'CY', 0, 'Cyprus', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(56, NULL, 'CZ', 'CZ', 0, 'Czechia', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(57, NULL, 'DE', 'DE', 0, 'Germany', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(58, NULL, 'DJ', 'DJ', 0, 'Djibouti', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(59, NULL, 'DK', 'DK', 0, 'Denmark', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(60, NULL, 'DM', 'DM', 0, 'Dominica', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(61, NULL, 'DO', 'DO', 0, 'Dominican Republic', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(62, NULL, 'DZ', 'DZ', 0, 'Algeria', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(63, NULL, 'EC', 'EC', 0, 'Ecuador', 'SA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(64, NULL, 'EE', 'EE', 0, 'Estonia', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(65, NULL, 'EG', 'EG', 0, 'Egypt', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(66, NULL, 'EH', 'EH', 0, 'Western Sahara', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(67, NULL, 'ER', 'ER', 0, 'Eritrea', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(68, NULL, 'ES', 'ES', 0, 'Spain', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(69, NULL, 'ET', 'ET', 0, 'Ethiopia', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(70, NULL, 'FI', 'FI', 0, 'Finland', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(71, NULL, 'FJ', 'FJ', 0, 'Fiji', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(72, NULL, 'FK', 'FK', 0, 'Falkland Islands', 'SA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(73, NULL, 'FM', 'FM', 0, 'Micronesia', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(74, NULL, 'FO', 'FO', 0, 'Faroe Islands', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(75, NULL, 'FR', 'FR', 0, 'France', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(76, NULL, 'GA', 'GA', 0, 'Gabon', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(77, NULL, 'GB', 'GB', 0, 'United Kingdom', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(78, NULL, 'GD', 'GD', 0, 'Grenada', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(79, NULL, 'GE', 'GE', 0, 'Georgia', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(80, NULL, 'GF', 'GF', 0, 'French Guiana', 'SA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(81, NULL, 'GG', 'GG', 0, 'Guernsey', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(82, NULL, 'GH', 'GH', 0, 'Ghana', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(83, NULL, 'GI', 'GI', 0, 'Gibraltar', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(84, NULL, 'GL', 'GL', 0, 'Greenland', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(85, NULL, 'GM', 'GM', 0, 'The Gambia', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(86, NULL, 'GN', 'GN', 0, 'Guinea', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(87, NULL, 'GP', 'GP', 0, 'Guadeloupe', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(88, NULL, 'GQ', 'GQ', 0, 'Equatorial Guinea', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(89, NULL, 'GR', 'GR', 0, 'Greece', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(90, NULL, 'GS', 'GS', 0, 'South Georgia and South Sandwich Islands', 'AN', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(91, NULL, 'GT', 'GT', 0, 'Guatemala', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(92, NULL, 'GU', 'GU', 0, 'Guam', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(93, NULL, 'GW', 'GW', 0, 'Guinea-Bissau', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(94, NULL, 'GY', 'GY', 0, 'Guyana', 'SA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(95, NULL, 'HK', 'HK', 0, 'Hong Kong', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(96, NULL, 'HM', 'HM', 0, 'Heard and McDonald Islands', 'AN', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(97, NULL, 'HN', 'HN', 0, 'Honduras', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(98, NULL, 'HR', 'HR', 0, 'Croatia', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(99, NULL, 'HT', 'HT', 0, 'Haiti', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(100, NULL, 'HU', 'HU', 0, 'Hungary', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(101, NULL, 'ID', 'ID', 0, 'Indonesia', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(102, NULL, 'IE', 'IE', 0, 'Ireland', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(103, NULL, 'IL', 'IL', 0, 'Israel', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(104, NULL, 'IM', 'IM', 0, 'Isle of Man', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(105, NULL, 'IN', 'IN', 0, 'India', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(106, NULL, 'IO', 'IO', 0, 'British Indian Ocean Territory', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(107, NULL, 'IQ', 'IQ', 0, 'Iraq', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(108, NULL, 'IR', 'IR', 0, 'Iran', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(109, NULL, 'IS', 'IS', 0, 'Iceland', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(110, NULL, 'IT', 'IT', 0, 'Italy', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(111, NULL, 'JE', 'JE', 0, 'Jersey', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(112, NULL, 'JM', 'JM', 0, 'Jamaica', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(113, NULL, 'JO', 'JO', 0, 'Jordan', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(114, NULL, 'JP', 'JP', 0, 'Japan', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(115, NULL, 'KE', 'KE', 0, 'Kenya', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(116, NULL, 'KG', 'KG', 0, 'Kyrgyzstan', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(117, NULL, 'KH', 'KH', 0, 'Cambodia', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(118, NULL, 'KI', 'KI', 0, 'Kiribati', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(119, NULL, 'KM', 'KM', 0, 'Comoros', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(120, NULL, 'KN', 'KN', 0, 'St Kitts and Nevis', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(121, NULL, 'KP', 'KP', 0, 'North Korea', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(122, NULL, 'KR', 'KR', 0, 'South Korea', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(123, NULL, 'KW', 'KW', 0, 'Kuwait', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(124, NULL, 'KY', 'KY', 0, 'Cayman Islands', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(125, NULL, 'KZ', 'KZ', 0, 'Kazakhstan', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(126, NULL, 'LA', 'LA', 0, 'Laos', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(127, NULL, 'LB', 'LB', 0, 'Lebanon', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(128, NULL, 'LC', 'LC', 0, 'Saint Lucia', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(129, NULL, 'LI', 'LI', 0, 'Liechtenstein', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(130, NULL, 'LK', 'LK', 0, 'Sri Lanka', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(131, NULL, 'LR', 'LR', 0, 'Liberia', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(132, NULL, 'LS', 'LS', 0, 'Lesotho', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(133, NULL, 'LT', 'LT', 0, 'Lithuania', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(134, NULL, 'LU', 'LU', 0, 'Luxembourg', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(135, NULL, 'LV', 'LV', 0, 'Latvia', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(136, NULL, 'LY', 'LY', 0, 'Libya', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(137, NULL, 'MA', 'MA', 0, 'Morocco', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(138, NULL, 'MC', 'MC', 0, 'Monaco', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(139, NULL, 'MD', 'MD', 0, 'Moldova', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(140, NULL, 'ME', 'ME', 0, 'Montenegro', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(141, NULL, 'MF', 'MF', 0, 'Saint Martin', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(142, NULL, 'MG', 'MG', 0, 'Madagascar', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(143, NULL, 'MH', 'MH', 0, 'Marshall Islands', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(144, NULL, 'MK', 'MK', 0, 'North Macedonia', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(145, NULL, 'ML', 'ML', 0, 'Mali', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(146, NULL, 'MM', 'MM', 0, 'Myanmar', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(147, NULL, 'MN', 'MN', 0, 'Mongolia', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(148, NULL, 'MO', 'MO', 0, 'Macao', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(149, NULL, 'MP', 'MP', 0, 'Northern Mariana Islands', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(150, NULL, 'MQ', 'MQ', 0, 'Martinique', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(151, NULL, 'MR', 'MR', 0, 'Mauritania', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(152, NULL, 'MS', 'MS', 0, 'Montserrat', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(153, NULL, 'MT', 'MT', 0, 'Malta', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(154, NULL, 'MU', 'MU', 0, 'Mauritius', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(155, NULL, 'MV', 'MV', 0, 'Maldives', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(156, NULL, 'MW', 'MW', 0, 'Malawi', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(157, NULL, 'MX', 'MX', 0, 'Mexico', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(158, NULL, 'MY', 'MY', 0, 'Malaysia', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(159, NULL, 'MZ', 'MZ', 0, 'Mozambique', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(160, NULL, 'NA', 'NA', 0, 'Namibia', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(161, NULL, 'NC', 'NC', 0, 'New Caledonia', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(162, NULL, 'NE', 'NE', 0, 'Niger', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(163, NULL, 'NF', 'NF', 0, 'Norfolk Island', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(164, NULL, 'NG', 'NG', 0, 'Nigeria', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(165, NULL, 'NI', 'NI', 0, 'Nicaragua', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(166, NULL, 'NL', 'NL', 0, 'The Netherlands', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(167, NULL, 'NO', 'NO', 0, 'Norway', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(168, NULL, 'NP', 'NP', 0, 'Nepal', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(169, NULL, 'NR', 'NR', 0, 'Nauru', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(170, NULL, 'NU', 'NU', 0, 'Niue', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(171, NULL, 'NZ', 'NZ', 0, 'New Zealand', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(172, NULL, 'OM', 'OM', 0, 'Oman', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(173, NULL, 'PA', 'PA', 0, 'Panama', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(174, NULL, 'PE', 'PE', 0, 'Peru', 'SA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(175, NULL, 'PF', 'PF', 0, 'French Polynesia', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(176, NULL, 'PG', 'PG', 0, 'Papua New Guinea', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(177, NULL, 'PH', 'PH', 0, 'Philippines', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(178, NULL, 'PK', 'PK', 0, 'Pakistan', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(179, NULL, 'PL', 'PL', 0, 'Poland', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(180, NULL, 'PM', 'PM', 0, 'Saint Pierre and Miquelon', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(181, NULL, 'PN', 'PN', 0, 'Pitcairn Islands', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(182, NULL, 'PR', 'PR', 0, 'Puerto Rico', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(183, NULL, 'PS', 'PS', 0, 'Palestine', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(184, NULL, 'PT', 'PT', 0, 'Portugal', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(185, NULL, 'PW', 'PW', 0, 'Palau', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(186, NULL, 'PY', 'PY', 0, 'Paraguay', 'SA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(187, NULL, 'QA', 'QA', 0, 'Qatar', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(188, NULL, 'RE', 'RE', 0, 'Réunion', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(189, NULL, 'RO', 'RO', 0, 'Romania', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(190, NULL, 'RS', 'RS', 0, 'Serbia', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(191, NULL, 'RU', 'RU', 0, 'Russia', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(192, NULL, 'RW', 'RW', 0, 'Rwanda', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(193, NULL, 'SA', 'SA', 0, 'Saudi Arabia', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(194, NULL, 'SB', 'SB', 0, 'Solomon Islands', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(195, NULL, 'SC', 'SC', 0, 'Seychelles', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(196, NULL, 'SD', 'SD', 0, 'Sudan', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(197, NULL, 'SE', 'SE', 0, 'Sweden', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(198, NULL, 'SG', 'SG', 0, 'Singapore', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(199, NULL, 'SH', 'SH', 0, 'Saint Helena', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(200, NULL, 'SI', 'SI', 0, 'Slovenia', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(201, NULL, 'SJ', 'SJ', 0, 'Svalbard and Jan Mayen', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(202, NULL, 'SK', 'SK', 0, 'Slovakia', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(203, NULL, 'SL', 'SL', 0, 'Sierra Leone', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(204, NULL, 'SM', 'SM', 0, 'San Marino', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(205, NULL, 'SN', 'SN', 0, 'Senegal', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(206, NULL, 'SO', 'SO', 0, 'Somalia', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(207, NULL, 'SR', 'SR', 0, 'Suriname', 'SA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(208, NULL, 'SS', 'SS', 0, 'South Sudan', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(209, NULL, 'ST', 'ST', 0, 'São Tomé and Príncipe', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(210, NULL, 'SV', 'SV', 0, 'El Salvador', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(211, NULL, 'SX', 'SX', 0, 'Sint Maarten', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(212, NULL, 'SY', 'SY', 0, 'Syria', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(213, NULL, 'SZ', 'SZ', 0, 'Eswatini', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(214, NULL, 'TC', 'TC', 0, 'Turks and Caicos Islands', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(215, NULL, 'TD', 'TD', 0, 'Chad', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(216, NULL, 'TF', 'TF', 0, 'French Southern Territories', 'AN', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(217, NULL, 'TG', 'TG', 0, 'Togo', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(218, NULL, 'TH', 'TH', 0, 'Thailand', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(219, NULL, 'TJ', 'TJ', 0, 'Tajikistan', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(220, NULL, 'TK', 'TK', 0, 'Tokelau', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(221, NULL, 'TL', 'TL', 0, 'Timor-Leste', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(222, NULL, 'TM', 'TM', 0, 'Turkmenistan', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(223, NULL, 'TN', 'TN', 0, 'Tunisia', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(224, NULL, 'TO', 'TO', 0, 'Tonga', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(225, NULL, 'TR', 'TR', 0, 'Türkiye', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(226, NULL, 'TT', 'TT', 0, 'Trinidad and Tobago', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(227, NULL, 'TV', 'TV', 0, 'Tuvalu', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(228, NULL, 'TW', 'TW', 0, 'Taiwan', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(229, NULL, 'TZ', 'TZ', 0, 'Tanzania', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(230, NULL, 'UA', 'UA', 0, 'Ukraine', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(231, NULL, 'UG', 'UG', 0, 'Uganda', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(232, NULL, 'UM', 'UM', 0, 'U.S. Outlying Islands', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(233, NULL, 'US', 'US', 0, 'United States', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(234, NULL, 'UY', 'UY', 0, 'Uruguay', 'SA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(235, NULL, 'UZ', 'UZ', 0, 'Uzbekistan', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(236, NULL, 'VA', 'VA', 0, 'Vatican City', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(237, NULL, 'VC', 'VC', 0, 'St Vincent and Grenadines', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(238, NULL, 'VE', 'VE', 0, 'Venezuela', 'SA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(239, NULL, 'VG', 'VG', 0, 'British Virgin Islands', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(240, NULL, 'VI', 'VI', 0, 'U.S. Virgin Islands', 'NA', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(241, NULL, 'VN', 'VN', 0, 'Vietnam', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(242, NULL, 'VU', 'VU', 0, 'Vanuatu', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(243, NULL, 'WF', 'WF', 0, 'Wallis and Futuna', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(244, NULL, 'WS', 'WS', 0, 'Samoa', 'OC', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(245, NULL, 'XK', 'XK', 0, 'Kosovo', 'EU', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(246, NULL, 'YE', 'YE', 0, 'Yemen', 'AS', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(247, NULL, 'YT', 'YT', 0, 'Mayotte', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(248, NULL, 'ZA', 'ZA', 0, 'South Africa', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(249, NULL, 'ZM', 'ZM', 0, 'Zambia', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(250, NULL, 'ZW', 'ZW', 0, 'Zimbabwe', 'AF', 0, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());

-- ==================== China provinces (level=1, parent=CN) ====================
INSERT INTO `phpyun_region` (id, parent_id, country_code, code, level, name, continent, sort, status, created_at, updated_at) VALUES
(251, 48, 'CN', 'CN-BJ', 1, '北京', NULL, 1, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(252, 48, 'CN', 'CN-SH', 1, '上海', NULL, 2, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(253, 48, 'CN', 'CN-TJ', 1, '天津', NULL, 3, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(254, 48, 'CN', 'CN-CQ', 1, '重庆', NULL, 4, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(255, 48, 'CN', 'CN-GD', 1, '广东', NULL, 5, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(256, 48, 'CN', 'CN-JS', 1, '江苏', NULL, 6, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(257, 48, 'CN', 'CN-ZJ', 1, '浙江', NULL, 7, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(258, 48, 'CN', 'CN-SD', 1, '山东', NULL, 8, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(259, 48, 'CN', 'CN-FJ', 1, '福建', NULL, 9, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(260, 48, 'CN', 'CN-SC', 1, '四川', NULL, 10, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(261, 48, 'CN', 'CN-HB', 1, '湖北', NULL, 11, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(262, 48, 'CN', 'CN-HN', 1, '湖南', NULL, 12, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(263, 48, 'CN', 'CN-HA', 1, '河南', NULL, 13, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(264, 48, 'CN', 'CN-HE', 1, '河北', NULL, 14, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(265, 48, 'CN', 'CN-AH', 1, '安徽', NULL, 15, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(266, 48, 'CN', 'CN-JX', 1, '江西', NULL, 16, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(267, 48, 'CN', 'CN-LN', 1, '辽宁', NULL, 17, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(268, 48, 'CN', 'CN-JL', 1, '吉林', NULL, 18, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(269, 48, 'CN', 'CN-HL', 1, '黑龙江', NULL, 19, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(270, 48, 'CN', 'CN-SX', 1, '山西', NULL, 20, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(271, 48, 'CN', 'CN-SN', 1, '陕西', NULL, 21, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(272, 48, 'CN', 'CN-GS', 1, '甘肃', NULL, 22, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(273, 48, 'CN', 'CN-YN', 1, '云南', NULL, 23, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(274, 48, 'CN', 'CN-GZ', 1, '贵州', NULL, 24, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(275, 48, 'CN', 'CN-GX', 1, '广西', NULL, 25, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(276, 48, 'CN', 'CN-HI', 1, '海南', NULL, 26, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(277, 48, 'CN', 'CN-NM', 1, '内蒙古', NULL, 27, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(278, 48, 'CN', 'CN-NX', 1, '宁夏', NULL, 28, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(279, 48, 'CN', 'CN-QH', 1, '青海', NULL, 29, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(280, 48, 'CN', 'CN-XJ', 1, '新疆', NULL, 30, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(281, 48, 'CN', 'CN-XZ', 1, '西藏', NULL, 31, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(282, 48, 'CN', 'CN-HK', 1, '香港', NULL, 32, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(283, 48, 'CN', 'CN-MO', 1, '澳门', NULL, 33, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(284, 48, 'CN', 'CN-TW', 1, '台湾', NULL, 34, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());

-- ==================== Beijing districts (level=2, parent=CN-BJ) ====================
INSERT INTO `phpyun_region` (id, parent_id, country_code, code, level, name, continent, sort, status, created_at, updated_at) VALUES
(285, 251, 'CN', 'CN-BJ-CY', 2, '朝阳区', NULL, 1, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(286, 251, 'CN', 'CN-BJ-HD', 2, '海淀区', NULL, 2, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(287, 251, 'CN', 'CN-BJ-DC', 2, '东城区', NULL, 3, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(288, 251, 'CN', 'CN-BJ-XC', 2, '西城区', NULL, 4, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(289, 251, 'CN', 'CN-BJ-FT', 2, '丰台区', NULL, 5, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(290, 251, 'CN', 'CN-BJ-SJS', 2, '石景山区', NULL, 6, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(291, 251, 'CN', 'CN-BJ-TZ', 2, '通州区', NULL, 7, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(292, 251, 'CN', 'CN-BJ-CP', 2, '昌平区', NULL, 8, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(293, 251, 'CN', 'CN-BJ-DX', 2, '大兴区', NULL, 9, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(294, 251, 'CN', 'CN-BJ-SY', 2, '顺义区', NULL, 10, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());

-- ==================== Shanghai districts (level=2, parent=CN-SH) ====================
INSERT INTO `phpyun_region` (id, parent_id, country_code, code, level, name, continent, sort, status, created_at, updated_at) VALUES
(295, 252, 'CN', 'CN-SH-PD', 2, '浦东新区', NULL, 1, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(296, 252, 'CN', 'CN-SH-HP', 2, '黄浦区', NULL, 2, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(297, 252, 'CN', 'CN-SH-XH', 2, '徐汇区', NULL, 3, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(298, 252, 'CN', 'CN-SH-CN', 2, '长宁区', NULL, 4, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(299, 252, 'CN', 'CN-SH-JA', 2, '静安区', NULL, 5, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(300, 252, 'CN', 'CN-SH-PT', 2, '普陀区', NULL, 6, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(301, 252, 'CN', 'CN-SH-HK', 2, '虹口区', NULL, 7, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(302, 252, 'CN', 'CN-SH-YP', 2, '杨浦区', NULL, 8, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(303, 252, 'CN', 'CN-SH-MH', 2, '闵行区', NULL, 9, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(304, 252, 'CN', 'CN-SH-BS', 2, '宝山区', NULL, 10, 0, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());

-- Total seeded rows: 304
