-- English names for comclass / userclass / remaining industry.
-- Bundled at crates/products/recruit/services/data/{comclass,userclass,industry}-en.json.
-- INSERT IGNORE so admin edits in phpyun_dict_i18n are kept.
INSERT IGNORE INTO `phpyun_dict_i18n` (`kind`, `item_id`, `lang`, `text`) VALUES
('comclass', 12, 'en', 'Fresh graduate'),
('comclass', 13, 'en', '1+ years'),
('comclass', 14, 'en', '2+ years'),
('comclass', 15, 'en', '3+ years'),
('comclass', 16, 'en', '5+ years'),
('comclass', 17, 'en', '8+ years'),
('comclass', 18, 'en', '10+ years'),
('comclass', 20, 'en', 'Foreign-invested'),
('comclass', 21, 'en', 'Joint venture'),
('comclass', 23, 'en', 'Private'),
('comclass', 24, 'en', 'Joint-stock'),
('comclass', 25, 'en', 'Collective'),
('comclass', 27, 'en', 'Under 10'),
('comclass', 28, 'en', '10-50'),
('comclass', 29, 'en', '50-200'),
('comclass', 30, 'en', '200-500'),
('comclass', 31, 'en', '500-1000'),
('comclass', 32, 'en', '1000+'),
('comclass', 40, 'en', 'Several'),
('comclass', 41, 'en', '1-2'),
('comclass', 42, 'en', '3-4'),
('comclass', 43, 'en', '5-6'),
('comclass', 44, 'en', '7-8'),
('comclass', 45, 'en', '9-10'),
('comclass', 46, 'en', 'Negotiable'),
('comclass', 47, 'en', 'Under 1000'),
('comclass', 48, 'en', '1000 - 1999'),
('comclass', 49, 'en', '3000 - 4499'),
('comclass', 50, 'en', '4500 - 5999'),
('comclass', 51, 'en', '6000 - 7999'),
('comclass', 52, 'en', '8000 - 8999'),
('comclass', 53, 'en', '10000+'),
('comclass', 54, 'en', 'Any'),
('comclass', 57, 'en', 'Within 1 week'),
('comclass', 58, 'en', 'Within 2 weeks'),
('comclass', 59, 'en', 'Within 3 weeks'),
('comclass', 60, 'en', 'Within 1 month'),
('comclass', 65, 'en', 'Any'),
('comclass', 66, 'en', 'High school'),
('comclass', 67, 'en', 'Technical secondary'),
('comclass', 68, 'en', 'Associate'),
('comclass', 69, 'en', 'Bachelor'),
('comclass', 70, 'en', 'Master'),
('comclass', 71, 'en', 'Doctorate'),
('comclass', 72, 'en', 'Any'),
('comclass', 73, 'en', 'Married'),
('comclass', 79, 'en', 'Listed company'),
('comclass', 80, 'en', 'Government agency'),
('comclass', 81, 'en', 'Public institution'),
('comclass', 82, 'en', 'Other'),
('comclass', 83, 'en', '2000 - 2999'),
('comclass', 85, 'en', '18-25'),
('comclass', 86, 'en', 'Under 35'),
('comclass', 87, 'en', '35+'),
('comclass', 88, 'en', 'Any'),
('comclass', 90, 'en', 'Three insurances + housing fund'),
('comclass', 91, 'en', 'Five insurances + housing fund'),
('comclass', 92, 'en', 'Meals and lodging'),
('comclass', 93, 'en', 'Allowances'),
('comclass', 94, 'en', 'Year-end bonus'),
('comclass', 95, 'en', 'Incentive plan'),
('comclass', 96, 'en', 'Sales commission'),
('comclass', 97, 'en', 'Leave policy'),
('comclass', 98, 'en', 'Public holidays'),
('comclass', 100, 'en', 'Mandarin Level 1'),
('comclass', 101, 'en', 'Mandarin Level 2'),
('comclass', 102, 'en', 'Mandarin Level 3'),
('comclass', 103, 'en', 'English'),
('comclass', 104, 'en', 'Korean'),
('comclass', 105, 'en', 'German'),
('comclass', 106, 'en', 'French'),
('comclass', 107, 'en', 'Spanish'),
('comclass', 108, 'en', 'Cantonese'),
('comclass', 109, 'en', 'Hokkien'),
('comclass', 110, 'en', 'Shanghainese'),
('comclass', 112, 'en', 'Single'),
('comclass', 127, 'en', 'Any'),
('userclass', 8, 'en', 'Married'),
('userclass', 9, 'en', 'Below high school'),
('userclass', 11, 'en', 'Single'),
('userclass', 12, 'en', 'High school'),
('userclass', 13, 'en', 'Technical secondary'),
('userclass', 14, 'en', 'Associate'),
('userclass', 15, 'en', 'Bachelor'),
('userclass', 16, 'en', 'Master'),
('userclass', 17, 'en', 'Doctorate'),
('userclass', 18, 'en', 'Fresh graduate'),
('userclass', 19, 'en', '1+ years'),
('userclass', 20, 'en', '2+ years'),
('userclass', 21, 'en', '3+ years'),
('userclass', 22, 'en', '5+ years'),
('userclass', 23, 'en', '8+ years'),
('userclass', 24, 'en', '10+ years'),
('userclass', 30, 'en', 'Negotiable'),
('userclass', 31, 'en', 'Under 1000'),
('userclass', 32, 'en', '1000 - 1999'),
('userclass', 33, 'en', '2000 - 2999'),
('userclass', 34, 'en', '3000 - 4499'),
('userclass', 35, 'en', '4500 - 5999'),
('userclass', 36, 'en', '6000 - 7999'),
('userclass', 37, 'en', '8000 - 9999'),
('userclass', 38, 'en', '10000+'),
('userclass', 45, 'en', 'Immediate'),
('userclass', 46, 'en', 'Within 1 week'),
('userclass', 47, 'en', 'Within 3 weeks'),
('userclass', 48, 'en', 'Within 1 month'),
('userclass', 50, 'en', 'Within 3 months'),
('userclass', 51, 'en', 'Uncertain'),
('userclass', 57, 'en', 'Any'),
('userclass', 58, 'en', 'Full-time'),
('userclass', 59, 'en', 'Part-time'),
('userclass', 100, 'en', '4+ years'),
('userclass', 101, 'en', '6+ years'),
('userclass', 114, 'en', 'Left job, seeking new role'),
('userclass', 115, 'en', 'Employed, open to better roles'),
('userclass', 116, 'en', 'Other'),
('userclass', 161, 'en', 'Strong technical skills'),
('userclass', 162, 'en', 'Experienced'),
('userclass', 163, 'en', 'Sales expert'),
('userclass', 164, 'en', 'Digital talent'),
('userclass', 165, 'en', 'Senior management'),
('userclass', 201, 'en', 'Returnee'),
('userclass', 202, 'en', 'Fortune 500 executive'),
('userclass', 203, 'en', 'Senior engineer'),
('industry', 35, 'en', 'Computer / Internet'),
('industry', 36, 'en', 'Sales / Customer Service / Tech Support'),
('industry', 37, 'en', 'Accounting / Finance / Banking / Insurance'),
('industry', 38, 'en', 'Production / Operations / Procurement / Logistics'),
('industry', 39, 'en', 'Biotech / Pharma / Healthcare'),
('industry', 40, 'en', 'Advertising / Marketing / Media / Arts'),
('industry', 41, 'en', 'Construction / Real Estate'),
('industry', 42, 'en', 'HR / Admin / Senior Management'),
('industry', 43, 'en', 'Consulting / Legal / Education / Research'),
('industry', 44, 'en', 'Services'),
('industry', 45, 'en', 'Civil Service / Translation / Other'),
('industry', 835, 'en', 'Trade / Retail'),
('industry', 836, 'en', 'Chemical / Energy'),
('industry', 837, 'en', 'Machinery / Equipment / Technicians'),
('industry', 839, 'en', 'Telecom / Electronics');
