-- Stripe Hosted Checkout ledger: one row = site order + Stripe request/response.
-- RUN_MIGRATIONS_ON_BOOT=false: apply on `jobs` by hand.

CREATE TABLE IF NOT EXISTS `phpyun_rs_stripe_order` (
    `id`                                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uid`                                   INT UNSIGNED    NOT NULL,
    `usertype`                              TINYINT         NOT NULL DEFAULT 0,
    `order_no`                              VARCHAR(64)     NOT NULL,
    `company_order_id`                      INT UNSIGNED    NOT NULL DEFAULT 0,
    `order_kind`                            INT             NOT NULL DEFAULT 0,
    `package_code`                          VARCHAR(120)    NOT NULL DEFAULT '',
    `rating`                                INT             NOT NULL DEFAULT 0,
    `subject`                               VARCHAR(255)    NOT NULL DEFAULT '',
    `amount_cents`                          INT             NOT NULL DEFAULT 0,
    `amount_yuan`                           DECIMAL(18,2)   NOT NULL DEFAULT 0.00,
    `channel`                               VARCHAR(32)     NOT NULL DEFAULT 'stripe',
    `order_state`                           TINYINT         NOT NULL DEFAULT 0,
    `client_ip`                             VARCHAR(64)     NOT NULL DEFAULT '',
    `success_path`                          VARCHAR(255)    NOT NULL DEFAULT '',
    `settled`                               TINYINT         NOT NULL DEFAULT 0,
    `pay_tx_id`                             VARCHAR(191)    NOT NULL DEFAULT '',
    `created_at`                            INT UNSIGNED    NOT NULL DEFAULT 0,
    `updated_at`                            INT UNSIGNED    NOT NULL DEFAULT 0,
    `paid_at`                               INT UNSIGNED    NOT NULL DEFAULT 0,
    `req_mode`                              VARCHAR(32)     NOT NULL DEFAULT '',
    `req_ui_mode`                           VARCHAR(32)     NOT NULL DEFAULT '',
    `req_currency`                          VARCHAR(8)      NOT NULL DEFAULT '',
    `req_unit_amount`                       INT             NOT NULL DEFAULT 0,
    `req_product_name`                      VARCHAR(255)    NOT NULL DEFAULT '',
    `req_quantity`                          INT             NOT NULL DEFAULT 0,
    `req_success_url`                       VARCHAR(1024)   NOT NULL DEFAULT '',
    `req_cancel_url`                        VARCHAR(1024)   NOT NULL DEFAULT '',
    `req_client_reference_id`               VARCHAR(64)     NOT NULL DEFAULT '',
    `req_customer_email`                    VARCHAR(191)    NOT NULL DEFAULT '',
    `req_metadata_json`                     JSON            NULL,
    `req_body`                              MEDIUMTEXT      NULL,
    `req_stripe_version`                    VARCHAR(64)     NOT NULL DEFAULT '',
    `req_at`                                INT UNSIGNED    NOT NULL DEFAULT 0,
    `stripe_session_id`                     VARCHAR(255)    NOT NULL DEFAULT '',
    `stripe_object`                         VARCHAR(64)     NOT NULL DEFAULT '',
    `stripe_livemode`                       TINYINT         NOT NULL DEFAULT 0,
    `stripe_created`                        INT UNSIGNED    NOT NULL DEFAULT 0,
    `stripe_expires_at`                     INT UNSIGNED    NOT NULL DEFAULT 0,
    `stripe_status`                         VARCHAR(32)     NOT NULL DEFAULT '',
    `stripe_payment_status`                 VARCHAR(32)     NOT NULL DEFAULT '',
    `stripe_mode`                           VARCHAR(32)     NOT NULL DEFAULT '',
    `stripe_ui_mode`                        VARCHAR(32)     NOT NULL DEFAULT '',
    `stripe_currency`                       VARCHAR(8)      NOT NULL DEFAULT '',
    `stripe_amount_subtotal`                INT             NULL,
    `stripe_amount_total`                   INT             NULL,
    `stripe_amount_discount`                INT             NULL,
    `stripe_amount_shipping`                INT             NULL,
    `stripe_amount_tax`                     INT             NULL,
    `stripe_customer`                       VARCHAR(191)    NOT NULL DEFAULT '',
    `stripe_customer_email`                 VARCHAR(191)    NOT NULL DEFAULT '',
    `stripe_customer_account`               VARCHAR(191)    NOT NULL DEFAULT '',
    `stripe_customer_creation`              VARCHAR(32)     NOT NULL DEFAULT '',
    `stripe_customer_name`                  VARCHAR(255)    NOT NULL DEFAULT '',
    `stripe_customer_phone`                 VARCHAR(64)     NOT NULL DEFAULT '',
    `stripe_customer_tax_exempt`            VARCHAR(32)     NOT NULL DEFAULT '',
    `stripe_payment_intent`                 VARCHAR(191)    NOT NULL DEFAULT '',
    `stripe_payment_link`                   VARCHAR(191)    NOT NULL DEFAULT '',
    `stripe_setup_intent`                   VARCHAR(191)    NOT NULL DEFAULT '',
    `stripe_subscription`                   VARCHAR(191)    NOT NULL DEFAULT '',
    `stripe_invoice`                        VARCHAR(191)    NOT NULL DEFAULT '',
    `stripe_url`                            VARCHAR(2048)   NOT NULL DEFAULT '',
    `stripe_success_url`                    VARCHAR(1024)   NOT NULL DEFAULT '',
    `stripe_cancel_url`                     VARCHAR(1024)   NOT NULL DEFAULT '',
    `stripe_return_url`                     VARCHAR(1024)   NOT NULL DEFAULT '',
    `stripe_client_reference_id`            VARCHAR(64)     NOT NULL DEFAULT '',
    `stripe_locale`                         VARCHAR(32)     NOT NULL DEFAULT '',
    `stripe_submit_type`                    VARCHAR(32)     NOT NULL DEFAULT '',
    `stripe_billing_address_collection`     VARCHAR(32)     NOT NULL DEFAULT '',
    `stripe_payment_method_collection`      VARCHAR(32)     NOT NULL DEFAULT '',
    `stripe_payment_method_types`           VARCHAR(255)    NOT NULL DEFAULT '',
    `stripe_allowed_payment_method_types`   VARCHAR(255)    NOT NULL DEFAULT '',
    `stripe_excluded_payment_method_types`  VARCHAR(255)    NOT NULL DEFAULT '',
    `stripe_allow_promotion_codes`          TINYINT         NULL,
    `stripe_recovered_from`                 VARCHAR(191)    NOT NULL DEFAULT '',
    `stripe_redirect_on_completion`         VARCHAR(32)     NOT NULL DEFAULT '',
    `stripe_origin_context`                 VARCHAR(32)     NOT NULL DEFAULT '',
    `stripe_integration_identifier`         VARCHAR(191)    NOT NULL DEFAULT '',
    `stripe_automatic_tax_enabled`          TINYINT         NULL,
    `stripe_automatic_tax_status`           VARCHAR(32)     NOT NULL DEFAULT '',
    `stripe_payment_method`                 VARCHAR(191)    NOT NULL DEFAULT '',
    `stripe_latest_charge`                  VARCHAR(191)    NOT NULL DEFAULT '',
    `stripe_adaptive_pricing_json`          JSON            NULL,
    `stripe_after_expiration_json`          JSON            NULL,
    `stripe_automatic_tax_json`             JSON            NULL,
    `stripe_branding_settings_json`         JSON            NULL,
    `stripe_collected_information_json`     JSON            NULL,
    `stripe_consent_json`                   JSON            NULL,
    `stripe_consent_collection_json`        JSON            NULL,
    `stripe_custom_fields_json`             JSON            NULL,
    `stripe_custom_text_json`               JSON            NULL,
    `stripe_customer_details_json`          JSON            NULL,
    `stripe_currency_conversion_json`       JSON            NULL,
    `stripe_discounts_json`                 JSON            NULL,
    `stripe_invoice_creation_json`          JSON            NULL,
    `stripe_line_items_json`                JSON            NULL,
    `stripe_metadata_json`                  JSON            NULL,
    `stripe_name_collection_json`           JSON            NULL,
    `stripe_optional_items_json`            JSON            NULL,
    `stripe_payment_method_options_json`    JSON            NULL,
    `stripe_payment_method_configuration_json` JSON         NULL,
    `stripe_permissions_json`               JSON            NULL,
    `stripe_phone_number_collection_json`   JSON            NULL,
    `stripe_presentment_details_json`       JSON            NULL,
    `stripe_saved_payment_method_options_json` JSON         NULL,
    `stripe_shipping_address_collection_json` JSON          NULL,
    `stripe_shipping_cost_json`             JSON            NULL,
    `stripe_shipping_options_json`          JSON            NULL,
    `stripe_tax_id_collection_json`         JSON            NULL,
    `stripe_total_details_json`             JSON            NULL,
    `stripe_wallet_options_json`            JSON            NULL,
    `stripe_managed_payments_json`          JSON            NULL,
    `stripe_event_id`                       VARCHAR(191)    NOT NULL DEFAULT '',
    `stripe_event_type`                     VARCHAR(128)    NOT NULL DEFAULT '',
    `stripe_event_created`                  INT UNSIGNED    NOT NULL DEFAULT 0,
    `stripe_api_version`                    VARCHAR(64)     NOT NULL DEFAULT '',
    `stripe_event_json`                     JSON            NULL,
    `stripe_session_json`                   JSON            NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_order_no` (`order_no`),
    KEY `ix_uid` (`uid`),
    KEY `ix_session` (`stripe_session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
