/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/admin/account-logouts/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_account_logouts_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/account-logouts/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_account_logouts_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/account-merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_account_merge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_ads"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ads/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_ads_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ads/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update or soft-delete an ad (sending `"status":2` deletes; underlying UPDATE sets status=2) */
        post: operations["post_v1_admin_ads_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/app-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_app_versions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/app-versions/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_app_versions_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/app-versions/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_app_versions_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List audit log entries */
        post: operations["post_v1_admin_audit_log"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/broadcasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_broadcasts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/broadcasts/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_broadcasts_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/broadcasts/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_broadcasts_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_categories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/categories/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_categories_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/categories/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_categories_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/company-certs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review queue */
        post: operations["post_v1_admin_company_certs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/company-certs/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve / reject */
        post: operations["post_v1_admin_company_certs_review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_countries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/countries/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Soft-delete (`status = 2`). */
        post: operations["post_v1_admin_countries_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/countries/patch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_countries_patch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/countries/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force a cache reload from DB. Useful after a manual SQL bulk import. */
        post: operations["post_v1_admin_countries_reload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review queue + activity snapshot */
        post: operations["post_v1_admin_dashboard_overview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/dashboard/recent-signups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recent signups */
        post: operations["post_v1_admin_dashboard_recent_signups"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/desc-classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_desc_classes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/desc-classes/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_desc_classes_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/desc-classes/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update or soft-delete a class (passing `"status":2` in the body means delete) */
        post: operations["post_v1_admin_desc_classes_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/descriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_descriptions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/descriptions/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_descriptions_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/descriptions/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_descriptions_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/dict-i18n/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reload dictionaries + translation tables immediately and broadcast to the rest of the cluster. */
        post: operations["post_v1_admin_dict_i18n_reload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback list */
        post: operations["post_v1_admin_feedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/feedback/batch/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch mark as resolved */
        post: operations["post_v1_admin_feedback_batch_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/feedback/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark feedback as resolved */
        post: operations["post_v1_admin_feedback_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Job review queue */
        post: operations["post_v1_admin_jobs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/jobs/batch/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch review jobs */
        post: operations["post_v1_admin_jobs_batch_state"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/jobs/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review a job */
        post: operations["post_v1_admin_jobs_state"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/nav": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_nav"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/nav/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_nav_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/nav/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update or soft-delete a navigation entry (sending `"status":2` deletes it) */
        post: operations["post_v1_admin_nav_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Global order list */
        post: operations["post_v1_admin_orders"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/orders/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refund / cancel order */
        post: operations["post_v1_admin_orders_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/recycle-bin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recycle bin list */
        post: operations["post_v1_admin_recycle_bin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/recycle-bin/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Single record detail */
        post: operations["post_v1_admin_recycle_bin_detail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/recycle-bin/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Permanently delete */
        post: operations["post_v1_admin_recycle_bin_purge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/redeem-classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create class */
        post: operations["post_v1_admin_redeem_classes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/redeem-classes/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete class (including children) */
        post: operations["post_v1_admin_redeem_classes_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/redeem-classes/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List classes */
        post: operations["post_v1_admin_redeem_classes_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/redeem-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Order list */
        post: operations["post_v1_admin_redeem_orders"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/redeem-orders/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve order (no refund, awaiting shipment) */
        post: operations["post_v1_admin_redeem_orders_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/redeem-orders/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject order (refund integral + restore stock) */
        post: operations["post_v1_admin_redeem_orders_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_regions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/regions/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Soft-delete (`status=2`). Children are not auto-cascaded — the cache filters
         *     by `status != 2`, so descendants remain visible until the admin explicitly
         *     deletes them.
         */
        post: operations["post_v1_admin_regions_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/regions/patch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_regions_patch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/regions/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force a cluster-wide cache reload from DB (rarely needed; useful after a manual SQL bulk import). */
        post: operations["post_v1_admin_regions_reload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report queue */
        post: operations["post_v1_admin_reports"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/reports/batch/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch process reports */
        post: operations["post_v1_admin_reports_batch_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/reports/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process a report */
        post: operations["post_v1_admin_reports_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/rewards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create reward */
        post: operations["post_v1_admin_rewards"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/rewards/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete reward */
        post: operations["post_v1_admin_rewards_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/rewards/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommended / hot flags */
        post: operations["post_v1_admin_rewards_flags"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/rewards/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reward list */
        post: operations["post_v1_admin_rewards_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/rewards/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle online/offline */
        post: operations["post_v1_admin_rewards_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/site-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create / update setting */
        post: operations["post_v1_admin_site_settings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/site-settings/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete setting */
        post: operations["post_v1_admin_site_settings_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/site-settings/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** All settings (including non-public) */
        post: operations["post_v1_admin_site_settings_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User list (admin) */
        post: operations["post_v1_admin_users"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Freeze / unfreeze a user */
        post: operations["post_v1_admin_users_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/usertype-changes/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_usertype_changes_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/usertype-changes/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_v1_admin_usertype_changes_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/warnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin: issue a warning */
        post: operations["post_v1_admin_warnings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/warnings/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin: list warnings */
        post: operations["post_v1_admin_warnings_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdForm: {
            /** Format: int64 */
            end_at?: number;
            image: string;
            link: string;
            slot: string;
            /** Format: int64 */
            start_at?: number;
            title?: string;
            /** Format: int32 */
            weight?: number;
        };
        /** @description Ad management item — all 14 columns of phpyun_ad + formatted timestamps + derived is_active hint for the frontend button. */
        AdItem: {
            /** Format: int64 */
            created_at: number;
            created_at_n: string;
            /** Format: int64 */
            end_at: number;
            end_at_n: string;
            /** Format: int64 */
            id: number;
            image: string;
            link: string;
            pic_content: string;
            pic_height: string;
            pic_width: string;
            slot: string;
            /** Format: int64 */
            start_at: number;
            start_at_n: string;
            /** Format: int32 */
            status: number;
            /**
             * Format: int32
             * @description PHP `target`: 1=current window / 2=new window
             */
            target: number;
            title: string;
            /** Format: int32 */
            weight: number;
        };
        AdPatchForm: {
            /** Format: int64 */
            end_at?: number | null;
            /** Format: int64 */
            id: number;
            image?: string | null;
            link?: string | null;
            slot?: string | null;
            /** Format: int64 */
            start_at?: number | null;
            /**
             * Format: int32
             * @description 0=offline / 1=online / 2=deleted (soft delete)
             */
            status?: number | null;
            title?: string | null;
            /** Format: int32 */
            weight?: number | null;
        };
        AdminFeedbackItem: {
            category: string;
            client_ip: string;
            contact: string;
            content: string;
            /** Format: int64 */
            created_at: number;
            created_at_n: string;
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            status: number;
            status_n: string;
            /** Format: int64 */
            uid?: number | null;
        };
        AdminReportItem: {
            /** Format: int64 */
            created_at: number;
            created_at_n: string;
            detail?: string | null;
            /** Format: int64 */
            id: number;
            reason_code: string;
            /** Format: int64 */
            reporter_uid: number;
            /** Format: int32 */
            status: number;
            status_n: string;
            /** Format: int64 */
            target_id: number;
            /** Format: int32 */
            target_kind: number;
            target_kind_n: string;
        };
        /** @description User management item — phpyun_member exposed columns (password / salt are not output) + derived usertype/status text + formatted timestamps. */
        AdminUserItem: {
            /** Format: int64 */
            did: number;
            email?: string | null;
            /** Format: int64 */
            login_date?: number | null;
            login_date_n: string;
            moblie?: string | null;
            /** Format: int64 */
            reg_date: number;
            reg_date_n: string;
            /** Format: int32 */
            status: number;
            status_n: string;
            /** Format: int64 */
            uid: number;
            username: string;
            /** Format: int32 */
            usertype: number;
            usertype_n: string;
        };
        AuditItem: {
            action: string;
            actor_ip: string;
            actor_ua: string;
            /** Format: int64 */
            actor_uid?: number | null;
            /** Format: int64 */
            created_at: number;
            created_at_n: string;
            /** Format: int64 */
            id: number;
            meta?: string | null;
            /** Format: int32 */
            success: number;
            target: string;
        };
        /**
         * @description `{ requested, affected }` — bulk-action result envelope. Used by every
         *     admin / employer batch-update / batch-delete endpoint to report how many
         *     items were *requested* (input length) vs. how many were *affected*
         *     (rows the DB actually touched, after auth-scoping and stale filters).
         */
        BatchResult: {
            /** Format: int64 */
            affected: number;
            requested: number;
        };
        BatchStateForm: {
            ids: number[];
            /** Format: int32 */
            state: number;
        };
        BatchStatusForm: {
            ids: number[];
            /** Format: int32 */
            status: number;
        };
        BroadcastItem: {
            body: string;
            /** Format: int64 */
            created_at: number;
            created_at_n: string;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            issuer_uid: number;
            /** Format: int32 */
            status: number;
            /** Format: int32 */
            target_usertype: number;
            target_usertype_n: string;
            title: string;
        };
        CatForm: {
            kind: string;
            name: string;
            /** Format: int64 */
            parent_id?: number;
            /** Format: int32 */
            sort?: number;
        };
        CatItem: {
            /** Format: int64 */
            id: number;
            kind: string;
            name: string;
            /** Format: int64 */
            parent_id: number;
            /** Format: int32 */
            sort: number;
            /** Format: int32 */
            status: number;
            /** Format: int64 */
            updated_at: number;
            updated_at_n: string;
        };
        CatPatchForm: {
            /** Format: int64 */
            id: number;
            name?: string | null;
            /** Format: int64 */
            parent_id?: number | null;
            /** Format: int32 */
            sort?: number | null;
            /**
             * Format: int32
             * @description 0=offline / 1=online / 2=deleted (soft delete)
             */
            status?: number | null;
        };
        /** @description Admin review queue item — all 10 columns of phpyun_company_cert + CDN URL + formatted timestamps + status name. */
        CertItem: {
            /** Format: int64 */
            created_at: number;
            created_at_n: string;
            id_photo: string;
            id_photo_n: string;
            license_photo: string;
            license_photo_n: string;
            note: string;
            /** Format: int64 */
            reviewed_at: number;
            reviewed_at_n: string;
            /** Format: int64 */
            reviewer_uid: number;
            /** Format: int32 */
            status: number;
            status_n: string;
            /** Format: int64 */
            submitted_at: number;
            submitted_at_n: string;
            /** Format: int64 */
            uid: number;
            /** Format: int64 */
            updated_at: number;
            updated_at_n: string;
        };
        ClassForm: {
            name: string;
            /** Format: int32 */
            sort?: number;
        };
        ClassPatchForm: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            sort?: number | null;
            /**
             * Format: int32
             * @description Soft delete: pass `2` to delete the class.
             */
            status?: number | null;
        };
        CreateForm: {
            /** @description Stable identifier. ISO 3166-2 form: `CN-BJ` / `US-CA`. Lower levels add a custom suffix: `CN-BJ-CY`. */
            code: string;
            /** @description Optional `AF/AN/AS/EU/NA/OC/SA` (country-level only). */
            continent?: string | null;
            /** @description ISO 3166-1 alpha-2 (CN/US/...). For non-country rows this should match the country chain. */
            country_code: string;
            /**
             * Format: int32
             * @description 0=country, 1=state/province, 2=city, 3=district.
             */
            level: number;
            name: string;
            /**
             * Format: int64
             * @description `NULL` for country-level rows; otherwise a parent region's id.
             */
            parent_id?: number | null;
            /** Format: int32 */
            sort?: number;
        };
        /** @description `{ id }` — used as the create-result envelope across CRUD endpoints. */
        CreatedId: {
            /** Format: int64 */
            id: number;
        };
        FlagsForm: {
            /** Format: int64 */
            id: number;
            /**
             * Format: int32
             * @description 0 = unset, 1 = hot.
             */
            is_hot?: number | null;
            /**
             * Format: int32
             * @description 0 = unset, 1 = recommended. Anything else is rejected at validation.
             */
            is_rec?: number | null;
        };
        /** @description Body carrying just `{ id }`. Use for any "act on one resource by id" call. */
        IdBody: {
            /** Format: int64 */
            id: number;
        };
        /**
         * @description Job list item — aligned with the field set returned by PHPYun
         *     `JobM::getList()`. **Shape is shared across `wap`, `mcenter` and `admin`**
         *     so the front-end card component is identical regardless of the listing
         *     context.
         */
        JobSummary: {
            /** Format: int32 */
            city_id: number;
            com_logo?: string | null;
            com_name?: string | null;
            /** Format: int32 */
            edu: number;
            /**
             * @description Education-level name (PHP `comclass` dict, e.g. "本科") —
             *     filled by `job_summary_from_dict*`; empty for `From<Job>`.
             */
            edu_n: string;
            /** Format: int32 */
            exp: number;
            /**
             * @description Experience-tier name (PHP `comclass` dict, e.g. "5-10 年") —
             *     filled by `job_summary_from_dict*`; empty for `From<Job>`.
             */
            exp_n: string;
            /** Format: int32 */
            hy: number;
            /** Format: int64 */
            id: number;
            /**
             * @description Whether the *current* user has favorited this job. Always `false` for
             *     unauthenticated requests / non-favorite contexts.
             */
            is_favorited: boolean;
            is_rec: boolean;
            is_urgent: boolean;
            /** Format: int32 */
            job1: number;
            /** Format: int32 */
            job1_son: number;
            /** @description Province name (PHP `job_city_one`) */
            job_city_one: string;
            /** @description City name (PHP `job_city_two`) */
            job_city_two: string;
            job_hy: string;
            job_one_n: string;
            /** Format: int32 */
            job_post: number;
            job_three_n: string;
            job_two_n: string;
            /** Format: int32 */
            jobhits: number;
            /** @description Three-level job category joined as "Frontend / Web Frontend / React Developer" (PHP `jobname`) */
            jobname: string;
            /** Format: int64 */
            lastupdate: number;
            /** Format: int32 */
            max_salary: number;
            /** Format: int32 */
            min_salary: number;
            name: string;
            /**
             * @description Posted within the last 2 days (PHP `newtime`); requires `now` ts to
             *     derive — `From<Job>` leaves this `false`.
             */
            newtime: boolean;
            /** Format: int32 */
            province_id: number;
            /** Format: int32 */
            rec: number;
            /** Format: int64 */
            rec_time: number;
            /** Format: int32 */
            salary: number;
            /** Format: int64 */
            sdate: number;
            /** Format: int32 */
            three_city_id: number;
            /** Format: int64 */
            uid: number;
            /** Format: int32 */
            urgent: number;
            /** Format: int64 */
            urgent_time: number;
        };
        MergeDone: {
            /** Format: int64 */
            company_uid: number;
            /** Format: int64 */
            user_uid: number;
        };
        MergeForm: {
            /** Format: int64 */
            company_uid: number;
            /** Format: int64 */
            user_uid: number;
        };
        NavForm: {
            icon?: string;
            label: string;
            /** Format: int64 */
            parent_id?: number;
            position: string;
            /** Format: int32 */
            sort?: number;
            url: string;
        };
        /** @description Navigation item — all 9 columns of phpyun_navigation + CDN URL + formatted timestamp. */
        NavItem: {
            icon: string;
            icon_n: string;
            /** Format: int64 */
            id: number;
            label: string;
            /** Format: int64 */
            parent_id: number;
            position: string;
            /** Format: int32 */
            sort: number;
            /** Format: int32 */
            status: number;
            /** Format: int64 */
            updated_at: number;
            updated_at_n: string;
            url: string;
        };
        NavPatchForm: {
            icon?: string | null;
            /** Format: int64 */
            id: number;
            label?: string | null;
            /** Format: int64 */
            parent_id?: number | null;
            /** Format: int32 */
            sort?: number | null;
            /**
             * Format: int32
             * @description 0=offline / 1=online / 2=deleted (soft delete)
             */
            status?: number | null;
            url?: string | null;
        };
        /** @description Pay order item — all 10 columns of phpyun_pay_order + yuan-unit amount + time formatting. */
        OrderItem: {
            /** Format: int32 */
            amount_cents: number;
            /** Format: double */
            amount_yuan: number;
            channel: string;
            /** Format: int64 */
            created_at: number;
            created_at_n: string;
            /** Format: int64 */
            id: number;
            order_no: string;
            package_code: string;
            /** Format: int64 */
            paid_at: number;
            paid_at_n: string;
            pay_tx_id?: string | null;
            /**
             * Format: int32
             * @description 0 pending / 1 paid / 2 refunded / 3 cancelled
             */
            status: number;
            status_n: string;
            /** Format: int64 */
            uid: number;
        };
        OverviewView: {
            /** Format: int64 */
            active_companies: number;
            /** Format: int64 */
            active_jobs: number;
            /** Format: int64 */
            active_resumes: number;
            /** Format: int64 */
            pending_company_certs: number;
            /** Format: int64 */
            pending_feedback: number;
            /** Format: int64 */
            pending_jobs: number;
            /** Format: int64 */
            pending_reports: number;
            /** Format: int64 */
            today_new_jobs: number;
            /** Format: int64 */
            today_new_resumes: number;
            /** Format: int64 */
            total_users: number;
        };
        PatchForm: {
            continent?: string | null;
            /** Format: int64 */
            id: number;
            name?: string | null;
            /** Format: int32 */
            sort?: number | null;
        };
        RecentUser: {
            /** Format: int64 */
            did: number;
            email?: string | null;
            /** Format: int64 */
            login_date?: number | null;
            login_date_n: string;
            moblie?: string | null;
            /** Format: int64 */
            reg_date: number;
            reg_date_n: string;
            /** Format: int32 */
            status: number;
            status_n: string;
            /** Format: int64 */
            uid: number;
            username: string;
            /** Format: int32 */
            usertype: number;
            usertype_n: string;
        };
        RemoveBody: {
            key: string;
        };
        ReviewForm: {
            approve: boolean;
            note?: string;
            /** Format: int64 */
            uid: number;
        };
        RewardForm: {
            content?: string;
            /** Format: int32 */
            integral: number;
            name: string;
            /** Format: int64 */
            nid?: number;
            pic?: string;
            /** Format: int32 */
            restriction?: number;
            /** Format: int32 */
            stock?: number;
            /** Format: int64 */
            tnid?: number;
        };
        SetFeedbackStatusForm: {
            /** Format: int64 */
            id: number;
            /**
             * Format: int32
             * @description 1=resolved
             */
            status: number;
        };
        SetJobStateForm: {
            /** Format: int64 */
            id: number;
            /**
             * Format: int32
             * @description 1=approved / 2=rejected
             */
            state: number;
        };
        SetReportStatusForm: {
            /** Format: int64 */
            id: number;
            /**
             * Format: int32
             * @description 1=approved / 2=rejected
             */
            status: number;
        };
        SetStatusForm: {
            /**
             * Format: int32
             * @description 0=frozen / 1=active
             */
            status: number;
            /** Format: int64 */
            uid: number;
        };
        SettingItem: {
            description: string;
            is_public: boolean;
            /** Format: int32 */
            is_public_int: number;
            key: string;
            /** Format: int64 */
            updated_at: number;
            updated_at_n: string;
            value: string;
        };
        /**
         * @description `{ status: Option<i32> }` — admin list filter envelope. The 0..=99 bound is
         *     permissive on purpose; handlers further interpret the value (0=pending,
         *     1=approved, ...) via service logic.
         */
        StatusFilterBody: {
            /** Format: int32 */
            status?: number | null;
        };
        StatusForm: {
            /** Format: int64 */
            id: number;
            /**
             * Format: int32
             * @description 0=offline  1=online
             */
            status: number;
        };
        UpsertForm: {
            description?: string;
            is_public?: boolean;
            key: string;
            value: string;
        };
        VersionItem: {
            changelog: string;
            /** Format: int64 */
            created_at: number;
            created_at_n: string;
            download_url: string;
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            is_force: number;
            platform: string;
            /** Format: int64 */
            released_at: number;
            released_at_n: string;
            /** Format: int32 */
            status: number;
            version: string;
            /** Format: int32 */
            version_code: number;
        };
        WarnForm: {
            reason: string;
            /** Format: int64 */
            target_id?: number;
            /**
             * Format: int32
             * @description 1=user 2=company 3=job 4=resume
             */
            target_kind: number;
            /** Format: int64 */
            target_uid: number;
        };
        WarningItem: {
            /** Format: int64 */
            created_at: number;
            created_at_n: string;
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            is_read: number;
            is_read_bool: boolean;
            /** Format: int64 */
            issuer_uid: number;
            reason: string;
            /** Format: int64 */
            target_id: number;
            /** Format: int32 */
            target_kind: number;
            target_kind_n: string;
            /** Format: int64 */
            target_uid: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_v1_admin_account_logouts_approve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_account_logouts_reject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_account_merge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MergeDone"];
                };
            };
            /** @description Invalid uid / precondition check failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_ads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedId"];
                };
            };
        };
    };
    post_v1_admin_ads_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_ads_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdPatchForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_app_versions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedId"];
                };
            };
        };
    };
    post_v1_admin_app_versions_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_app_versions_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_audit_log: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description e.g. `admin.` / `user.` */
                action_prefix: string | null;
                actor_uid: number | null;
                since: number | null;
                until: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_broadcasts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedId"];
                };
            };
        };
    };
    post_v1_admin_broadcasts_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_broadcasts_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_categories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedId"];
                };
            };
        };
    };
    post_v1_admin_categories_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_categories_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatPatchForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_company_certs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_company_certs_review: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_countries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateForm"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedId"];
                };
            };
            /** @description Admin required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_countries_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdBody"];
            };
        };
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_countries_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_countries_reload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reloaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_dashboard_overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewView"];
                };
            };
        };
    };
    post_v1_admin_dashboard_recent_signups: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                limit: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_desc_classes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedId"];
                };
            };
        };
    };
    post_v1_admin_desc_classes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_desc_classes_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassPatchForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_descriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedId"];
                };
            };
        };
    };
    post_v1_admin_descriptions_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_descriptions_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_id: number | null;
                /** @description Default false (admin sees everything) */
                only_visible: boolean;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_dict_i18n_reload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_feedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusFilterBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_feedback_batch_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchStatusForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResult"];
                };
            };
        };
    };
    post_v1_admin_feedback_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetFeedbackStatusForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_jobs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 0=pending / 1=approved / 2=rejected */
                state: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_jobs_batch_state: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchStateForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResult"];
                };
            };
        };
    };
    post_v1_admin_jobs_state: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetJobStateForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_nav: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NavForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedId"];
                };
            };
        };
    };
    post_v1_admin_nav_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_nav_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NavPatchForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_orders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusFilterBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_orders_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStatusForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_recycle_bin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tablename: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_recycle_bin_detail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_recycle_bin_purge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_redeem_classes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedId"];
                };
            };
        };
    };
    post_v1_admin_redeem_classes_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_redeem_classes_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parent_id: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_redeem_orders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusFilterBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_redeem_orders_approve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_redeem_orders_reject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_regions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateForm"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedId"];
                };
            };
            /** @description Admin required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_regions_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdBody"];
            };
        };
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_regions_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_regions_reload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reloaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_reports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusFilterBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_reports_batch_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchStatusForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResult"];
                };
            };
        };
    };
    post_v1_admin_reports_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetReportStatusForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_rewards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RewardForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedId"];
                };
            };
        };
    };
    post_v1_admin_rewards_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_rewards_flags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlagsForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_rewards_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Default false (admin sees everything) */
                only_active: boolean;
                nid: number | null;
                tnid: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_rewards_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_site_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_site_settings_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_site_settings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_users: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyword: string | null;
                usertype: number | null;
                status: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_users_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStatusForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_usertype_changes_approve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_usertype_changes_reject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdBody"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_v1_admin_warnings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WarnForm"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedId"];
                };
            };
        };
    };
    post_v1_admin_warnings_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
